// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/ic/v1/ic_service.proto

// Package v1 ic provides protocol buffer versions of the DAM API, allowing
// end points to receive requests and returns responses using these messages.

package v1

import (
	fmt "fmt"
	v1 "github.com/GoogleCloudPlatform/healthcare-federated-access-services/proto/common/v1"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IcConfig struct {
	Version              string                          `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Revision             int64                           `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	CommitTime           float64                         `protobuf:"fixed64,3,opt,name=commit_time,json=commitTime,proto3" json:"commit_time,omitempty"`
	IdentityProviders    map[string]*v1.IdentityProvider `protobuf:"bytes,4,rep,name=identity_providers,json=identityProviders,proto3" json:"identity_providers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Clients              map[string]*v1.Client           `protobuf:"bytes,5,rep,name=clients,proto3" json:"clients,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Options              *ConfigOptions                  `protobuf:"bytes,7,opt,name=options,proto3" json:"options,omitempty"`
	Ui                   map[string]string               `protobuf:"bytes,8,rep,name=ui,proto3" json:"ui,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *IcConfig) Reset()         { *m = IcConfig{} }
func (m *IcConfig) String() string { return proto.CompactTextString(m) }
func (*IcConfig) ProtoMessage()    {}
func (*IcConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{0}
}

func (m *IcConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IcConfig.Unmarshal(m, b)
}
func (m *IcConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IcConfig.Marshal(b, m, deterministic)
}
func (m *IcConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IcConfig.Merge(m, src)
}
func (m *IcConfig) XXX_Size() int {
	return xxx_messageInfo_IcConfig.Size(m)
}
func (m *IcConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_IcConfig.DiscardUnknown(m)
}

var xxx_messageInfo_IcConfig proto.InternalMessageInfo

func (m *IcConfig) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *IcConfig) GetRevision() int64 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *IcConfig) GetCommitTime() float64 {
	if m != nil {
		return m.CommitTime
	}
	return 0
}

func (m *IcConfig) GetIdentityProviders() map[string]*v1.IdentityProvider {
	if m != nil {
		return m.IdentityProviders
	}
	return nil
}

func (m *IcConfig) GetClients() map[string]*v1.Client {
	if m != nil {
		return m.Clients
	}
	return nil
}

func (m *IcConfig) GetOptions() *ConfigOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *IcConfig) GetUi() map[string]string {
	if m != nil {
		return m.Ui
	}
	return nil
}

type ConfigOptions struct {
	AccountNameLength       int32                     `protobuf:"varint,1,opt,name=account_name_length,json=accountNameLength,proto3" json:"account_name_length,omitempty"` // Deprecated: Do not use.
	ReadOnlyMasterRealm     bool                      `protobuf:"varint,2,opt,name=read_only_master_realm,json=readOnlyMasterRealm,proto3" json:"read_only_master_realm,omitempty"`
	DefaultPassportTokenTtl string                    `protobuf:"bytes,4,opt,name=default_passport_token_ttl,json=defaultPassportTokenTtl,proto3" json:"default_passport_token_ttl,omitempty"` // Deprecated: Do not use.
	MaxPassportTokenTtl     string                    `protobuf:"bytes,5,opt,name=max_passport_token_ttl,json=maxPassportTokenTtl,proto3" json:"max_passport_token_ttl,omitempty"`             // Deprecated: Do not use.
	AuthCodeTokenTtl        string                    `protobuf:"bytes,6,opt,name=auth_code_token_ttl,json=authCodeTokenTtl,proto3" json:"auth_code_token_ttl,omitempty"`                      // Deprecated: Do not use.
	AccessTokenTtl          string                    `protobuf:"bytes,7,opt,name=access_token_ttl,json=accessTokenTtl,proto3" json:"access_token_ttl,omitempty"`                              // Deprecated: Do not use.
	RefreshTokenTtl         string                    `protobuf:"bytes,8,opt,name=refresh_token_ttl,json=refreshTokenTtl,proto3" json:"refresh_token_ttl,omitempty"`                           // Deprecated: Do not use.
	ClaimTtlCap             string                    `protobuf:"bytes,9,opt,name=claim_ttl_cap,json=claimTtlCap,proto3" json:"claim_ttl_cap,omitempty"`
	ComputedDescriptors     map[string]*v1.Descriptor `protobuf:"bytes,10,rep,name=computed_descriptors,json=descriptors,proto3" json:"computed_descriptors,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral    struct{}                  `json:"-"`
	XXX_unrecognized        []byte                    `json:"-"`
	XXX_sizecache           int32                     `json:"-"`
}

func (m *ConfigOptions) Reset()         { *m = ConfigOptions{} }
func (m *ConfigOptions) String() string { return proto.CompactTextString(m) }
func (*ConfigOptions) ProtoMessage()    {}
func (*ConfigOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{1}
}

func (m *ConfigOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigOptions.Unmarshal(m, b)
}
func (m *ConfigOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigOptions.Marshal(b, m, deterministic)
}
func (m *ConfigOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigOptions.Merge(m, src)
}
func (m *ConfigOptions) XXX_Size() int {
	return xxx_messageInfo_ConfigOptions.Size(m)
}
func (m *ConfigOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigOptions proto.InternalMessageInfo

// Deprecated: Do not use.
func (m *ConfigOptions) GetAccountNameLength() int32 {
	if m != nil {
		return m.AccountNameLength
	}
	return 0
}

func (m *ConfigOptions) GetReadOnlyMasterRealm() bool {
	if m != nil {
		return m.ReadOnlyMasterRealm
	}
	return false
}

// Deprecated: Do not use.
func (m *ConfigOptions) GetDefaultPassportTokenTtl() string {
	if m != nil {
		return m.DefaultPassportTokenTtl
	}
	return ""
}

// Deprecated: Do not use.
func (m *ConfigOptions) GetMaxPassportTokenTtl() string {
	if m != nil {
		return m.MaxPassportTokenTtl
	}
	return ""
}

// Deprecated: Do not use.
func (m *ConfigOptions) GetAuthCodeTokenTtl() string {
	if m != nil {
		return m.AuthCodeTokenTtl
	}
	return ""
}

// Deprecated: Do not use.
func (m *ConfigOptions) GetAccessTokenTtl() string {
	if m != nil {
		return m.AccessTokenTtl
	}
	return ""
}

// Deprecated: Do not use.
func (m *ConfigOptions) GetRefreshTokenTtl() string {
	if m != nil {
		return m.RefreshTokenTtl
	}
	return ""
}

func (m *ConfigOptions) GetClaimTtlCap() string {
	if m != nil {
		return m.ClaimTtlCap
	}
	return ""
}

func (m *ConfigOptions) GetComputedDescriptors() map[string]*v1.Descriptor {
	if m != nil {
		return m.ComputedDescriptors
	}
	return nil
}

type IcSecrets struct {
	Version              string                          `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Revision             int64                           `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	CommitTime           float64                         `protobuf:"fixed64,3,opt,name=commit_time,json=commitTime,proto3" json:"commit_time,omitempty"`
	ClientSecrets        map[string]string               `protobuf:"bytes,4,rep,name=client_secrets,json=clientSecrets,proto3" json:"client_secrets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	IdProviderSecrets    map[string]string               `protobuf:"bytes,5,rep,name=id_provider_secrets,json=idProviderSecrets,proto3" json:"id_provider_secrets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	TokenKeys            map[string]*IcSecrets_TokenKeys `protobuf:"bytes,6,rep,name=token_keys,json=tokenKeys,proto3" json:"token_keys,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *IcSecrets) Reset()         { *m = IcSecrets{} }
func (m *IcSecrets) String() string { return proto.CompactTextString(m) }
func (*IcSecrets) ProtoMessage()    {}
func (*IcSecrets) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{2}
}

func (m *IcSecrets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IcSecrets.Unmarshal(m, b)
}
func (m *IcSecrets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IcSecrets.Marshal(b, m, deterministic)
}
func (m *IcSecrets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IcSecrets.Merge(m, src)
}
func (m *IcSecrets) XXX_Size() int {
	return xxx_messageInfo_IcSecrets.Size(m)
}
func (m *IcSecrets) XXX_DiscardUnknown() {
	xxx_messageInfo_IcSecrets.DiscardUnknown(m)
}

var xxx_messageInfo_IcSecrets proto.InternalMessageInfo

func (m *IcSecrets) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *IcSecrets) GetRevision() int64 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *IcSecrets) GetCommitTime() float64 {
	if m != nil {
		return m.CommitTime
	}
	return 0
}

func (m *IcSecrets) GetClientSecrets() map[string]string {
	if m != nil {
		return m.ClientSecrets
	}
	return nil
}

func (m *IcSecrets) GetIdProviderSecrets() map[string]string {
	if m != nil {
		return m.IdProviderSecrets
	}
	return nil
}

func (m *IcSecrets) GetTokenKeys() map[string]*IcSecrets_TokenKeys {
	if m != nil {
		return m.TokenKeys
	}
	return nil
}

type IcSecrets_TokenKeys struct {
	PrivateKey           string   `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	PublicKey            string   `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IcSecrets_TokenKeys) Reset()         { *m = IcSecrets_TokenKeys{} }
func (m *IcSecrets_TokenKeys) String() string { return proto.CompactTextString(m) }
func (*IcSecrets_TokenKeys) ProtoMessage()    {}
func (*IcSecrets_TokenKeys) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{2, 2}
}

func (m *IcSecrets_TokenKeys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IcSecrets_TokenKeys.Unmarshal(m, b)
}
func (m *IcSecrets_TokenKeys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IcSecrets_TokenKeys.Marshal(b, m, deterministic)
}
func (m *IcSecrets_TokenKeys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IcSecrets_TokenKeys.Merge(m, src)
}
func (m *IcSecrets_TokenKeys) XXX_Size() int {
	return xxx_messageInfo_IcSecrets_TokenKeys.Size(m)
}
func (m *IcSecrets_TokenKeys) XXX_DiscardUnknown() {
	xxx_messageInfo_IcSecrets_TokenKeys.DiscardUnknown(m)
}

var xxx_messageInfo_IcSecrets_TokenKeys proto.InternalMessageInfo

func (m *IcSecrets_TokenKeys) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func (m *IcSecrets_TokenKeys) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

type ReadOnlyConfig struct {
	DexUrl               string   `protobuf:"bytes,1,opt,name=dex_url,json=dexUrl,proto3" json:"dex_url,omitempty"`
	DexPort              string   `protobuf:"bytes,2,opt,name=dex_port,json=dexPort,proto3" json:"dex_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadOnlyConfig) Reset()         { *m = ReadOnlyConfig{} }
func (m *ReadOnlyConfig) String() string { return proto.CompactTextString(m) }
func (*ReadOnlyConfig) ProtoMessage()    {}
func (*ReadOnlyConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{3}
}

func (m *ReadOnlyConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadOnlyConfig.Unmarshal(m, b)
}
func (m *ReadOnlyConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadOnlyConfig.Marshal(b, m, deterministic)
}
func (m *ReadOnlyConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadOnlyConfig.Merge(m, src)
}
func (m *ReadOnlyConfig) XXX_Size() int {
	return xxx_messageInfo_ReadOnlyConfig.Size(m)
}
func (m *ReadOnlyConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadOnlyConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ReadOnlyConfig proto.InternalMessageInfo

func (m *ReadOnlyConfig) GetDexUrl() string {
	if m != nil {
		return m.DexUrl
	}
	return ""
}

func (m *ReadOnlyConfig) GetDexPort() string {
	if m != nil {
		return m.DexPort
	}
	return ""
}

type Realm struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Realm) Reset()         { *m = Realm{} }
func (m *Realm) String() string { return proto.CompactTextString(m) }
func (*Realm) ProtoMessage()    {}
func (*Realm) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{4}
}

func (m *Realm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Realm.Unmarshal(m, b)
}
func (m *Realm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Realm.Marshal(b, m, deterministic)
}
func (m *Realm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Realm.Merge(m, src)
}
func (m *Realm) XXX_Size() int {
	return xxx_messageInfo_Realm.Size(m)
}
func (m *Realm) XXX_DiscardUnknown() {
	xxx_messageInfo_Realm.DiscardUnknown(m)
}

var xxx_messageInfo_Realm proto.InternalMessageInfo

type ConfigModification struct {
	Revision             int64    `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	DryRun               bool     `protobuf:"varint,3,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigModification) Reset()         { *m = ConfigModification{} }
func (m *ConfigModification) String() string { return proto.CompactTextString(m) }
func (*ConfigModification) ProtoMessage()    {}
func (*ConfigModification) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{5}
}

func (m *ConfigModification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigModification.Unmarshal(m, b)
}
func (m *ConfigModification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigModification.Marshal(b, m, deterministic)
}
func (m *ConfigModification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigModification.Merge(m, src)
}
func (m *ConfigModification) XXX_Size() int {
	return xxx_messageInfo_ConfigModification.Size(m)
}
func (m *ConfigModification) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigModification.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigModification proto.InternalMessageInfo

func (m *ConfigModification) GetRevision() int64 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *ConfigModification) GetDryRun() bool {
	if m != nil {
		return m.DryRun
	}
	return false
}

type GetInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoRequest) Reset()         { *m = GetInfoRequest{} }
func (m *GetInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetInfoRequest) ProtoMessage()    {}
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{6}
}

func (m *GetInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoRequest.Unmarshal(m, b)
}
func (m *GetInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoRequest.Merge(m, src)
}
func (m *GetInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetInfoRequest.Size(m)
}
func (m *GetInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoRequest proto.InternalMessageInfo

type GetInfoResponse struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Versions             []string          `protobuf:"bytes,2,rep,name=versions,proto3" json:"versions,omitempty"`
	StartTime            int64             `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Modules              []string          `protobuf:"bytes,4,rep,name=modules,proto3" json:"modules,omitempty"`
	Ui                   map[string]string `protobuf:"bytes,5,rep,name=ui,proto3" json:"ui,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetInfoResponse) Reset()         { *m = GetInfoResponse{} }
func (m *GetInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetInfoResponse) ProtoMessage()    {}
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{7}
}

func (m *GetInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoResponse.Unmarshal(m, b)
}
func (m *GetInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoResponse.Merge(m, src)
}
func (m *GetInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetInfoResponse.Size(m)
}
func (m *GetInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoResponse proto.InternalMessageInfo

func (m *GetInfoResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetInfoResponse) GetVersions() []string {
	if m != nil {
		return m.Versions
	}
	return nil
}

func (m *GetInfoResponse) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *GetInfoResponse) GetModules() []string {
	if m != nil {
		return m.Modules
	}
	return nil
}

func (m *GetInfoResponse) GetUi() map[string]string {
	if m != nil {
		return m.Ui
	}
	return nil
}

type RealmRequest struct {
	Item                 *Realm   `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RealmRequest) Reset()         { *m = RealmRequest{} }
func (m *RealmRequest) String() string { return proto.CompactTextString(m) }
func (*RealmRequest) ProtoMessage()    {}
func (*RealmRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{8}
}

func (m *RealmRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RealmRequest.Unmarshal(m, b)
}
func (m *RealmRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RealmRequest.Marshal(b, m, deterministic)
}
func (m *RealmRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RealmRequest.Merge(m, src)
}
func (m *RealmRequest) XXX_Size() int {
	return xxx_messageInfo_RealmRequest.Size(m)
}
func (m *RealmRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RealmRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RealmRequest proto.InternalMessageInfo

func (m *RealmRequest) GetItem() *Realm {
	if m != nil {
		return m.Item
	}
	return nil
}

type RealmResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RealmResponse) Reset()         { *m = RealmResponse{} }
func (m *RealmResponse) String() string { return proto.CompactTextString(m) }
func (*RealmResponse) ProtoMessage()    {}
func (*RealmResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{9}
}

func (m *RealmResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RealmResponse.Unmarshal(m, b)
}
func (m *RealmResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RealmResponse.Marshal(b, m, deterministic)
}
func (m *RealmResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RealmResponse.Merge(m, src)
}
func (m *RealmResponse) XXX_Size() int {
	return xxx_messageInfo_RealmResponse.Size(m)
}
func (m *RealmResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RealmResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RealmResponse proto.InternalMessageInfo

type GetIdentityProvidersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIdentityProvidersRequest) Reset()         { *m = GetIdentityProvidersRequest{} }
func (m *GetIdentityProvidersRequest) String() string { return proto.CompactTextString(m) }
func (*GetIdentityProvidersRequest) ProtoMessage()    {}
func (*GetIdentityProvidersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{10}
}

func (m *GetIdentityProvidersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIdentityProvidersRequest.Unmarshal(m, b)
}
func (m *GetIdentityProvidersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIdentityProvidersRequest.Marshal(b, m, deterministic)
}
func (m *GetIdentityProvidersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIdentityProvidersRequest.Merge(m, src)
}
func (m *GetIdentityProvidersRequest) XXX_Size() int {
	return xxx_messageInfo_GetIdentityProvidersRequest.Size(m)
}
func (m *GetIdentityProvidersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIdentityProvidersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetIdentityProvidersRequest proto.InternalMessageInfo

type GetIdentityProvidersResponse struct {
	IdentityProviders    map[string]*v1.IdentityProvider `protobuf:"bytes,1,rep,name=identity_providers,json=identityProviders,proto3" json:"identity_providers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *GetIdentityProvidersResponse) Reset()         { *m = GetIdentityProvidersResponse{} }
func (m *GetIdentityProvidersResponse) String() string { return proto.CompactTextString(m) }
func (*GetIdentityProvidersResponse) ProtoMessage()    {}
func (*GetIdentityProvidersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{11}
}

func (m *GetIdentityProvidersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIdentityProvidersResponse.Unmarshal(m, b)
}
func (m *GetIdentityProvidersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIdentityProvidersResponse.Marshal(b, m, deterministic)
}
func (m *GetIdentityProvidersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIdentityProvidersResponse.Merge(m, src)
}
func (m *GetIdentityProvidersResponse) XXX_Size() int {
	return xxx_messageInfo_GetIdentityProvidersResponse.Size(m)
}
func (m *GetIdentityProvidersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIdentityProvidersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetIdentityProvidersResponse proto.InternalMessageInfo

func (m *GetIdentityProvidersResponse) GetIdentityProviders() map[string]*v1.IdentityProvider {
	if m != nil {
		return m.IdentityProviders
	}
	return nil
}

type GetTokenRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenRequest) Reset()         { *m = GetTokenRequest{} }
func (m *GetTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetTokenRequest) ProtoMessage()    {}
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{12}
}

func (m *GetTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenRequest.Unmarshal(m, b)
}
func (m *GetTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenRequest.Merge(m, src)
}
func (m *GetTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetTokenRequest.Size(m)
}
func (m *GetTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenRequest proto.InternalMessageInfo

type ConfigRequest struct {
	Item                 *IcConfig           `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Modification         *ConfigModification `protobuf:"bytes,2,opt,name=modification,proto3" json:"modification,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ConfigRequest) Reset()         { *m = ConfigRequest{} }
func (m *ConfigRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigRequest) ProtoMessage()    {}
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{13}
}

func (m *ConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigRequest.Unmarshal(m, b)
}
func (m *ConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigRequest.Marshal(b, m, deterministic)
}
func (m *ConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigRequest.Merge(m, src)
}
func (m *ConfigRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigRequest.Size(m)
}
func (m *ConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigRequest proto.InternalMessageInfo

func (m *ConfigRequest) GetItem() *IcConfig {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *ConfigRequest) GetModification() *ConfigModification {
	if m != nil {
		return m.Modification
	}
	return nil
}

type ConfigResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigResponse) Reset()         { *m = ConfigResponse{} }
func (m *ConfigResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigResponse) ProtoMessage()    {}
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{14}
}

func (m *ConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigResponse.Unmarshal(m, b)
}
func (m *ConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigResponse.Marshal(b, m, deterministic)
}
func (m *ConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigResponse.Merge(m, src)
}
func (m *ConfigResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigResponse.Size(m)
}
func (m *ConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigResponse proto.InternalMessageInfo

type ConfigIdentityProviderRequest struct {
	Item                 *v1.IdentityProvider `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Modification         *ConfigModification  `protobuf:"bytes,2,opt,name=modification,proto3" json:"modification,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ConfigIdentityProviderRequest) Reset()         { *m = ConfigIdentityProviderRequest{} }
func (m *ConfigIdentityProviderRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigIdentityProviderRequest) ProtoMessage()    {}
func (*ConfigIdentityProviderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{15}
}

func (m *ConfigIdentityProviderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigIdentityProviderRequest.Unmarshal(m, b)
}
func (m *ConfigIdentityProviderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigIdentityProviderRequest.Marshal(b, m, deterministic)
}
func (m *ConfigIdentityProviderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigIdentityProviderRequest.Merge(m, src)
}
func (m *ConfigIdentityProviderRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigIdentityProviderRequest.Size(m)
}
func (m *ConfigIdentityProviderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigIdentityProviderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigIdentityProviderRequest proto.InternalMessageInfo

func (m *ConfigIdentityProviderRequest) GetItem() *v1.IdentityProvider {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *ConfigIdentityProviderRequest) GetModification() *ConfigModification {
	if m != nil {
		return m.Modification
	}
	return nil
}

type ConfigIdProviderResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigIdProviderResponse) Reset()         { *m = ConfigIdProviderResponse{} }
func (m *ConfigIdProviderResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigIdProviderResponse) ProtoMessage()    {}
func (*ConfigIdProviderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{16}
}

func (m *ConfigIdProviderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigIdProviderResponse.Unmarshal(m, b)
}
func (m *ConfigIdProviderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigIdProviderResponse.Marshal(b, m, deterministic)
}
func (m *ConfigIdProviderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigIdProviderResponse.Merge(m, src)
}
func (m *ConfigIdProviderResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigIdProviderResponse.Size(m)
}
func (m *ConfigIdProviderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigIdProviderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigIdProviderResponse proto.InternalMessageInfo

type ConfigOptionsRequest struct {
	Item                 *ConfigOptions      `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Modification         *ConfigModification `protobuf:"bytes,2,opt,name=modification,proto3" json:"modification,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ConfigOptionsRequest) Reset()         { *m = ConfigOptionsRequest{} }
func (m *ConfigOptionsRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigOptionsRequest) ProtoMessage()    {}
func (*ConfigOptionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{17}
}

func (m *ConfigOptionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigOptionsRequest.Unmarshal(m, b)
}
func (m *ConfigOptionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigOptionsRequest.Marshal(b, m, deterministic)
}
func (m *ConfigOptionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigOptionsRequest.Merge(m, src)
}
func (m *ConfigOptionsRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigOptionsRequest.Size(m)
}
func (m *ConfigOptionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigOptionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigOptionsRequest proto.InternalMessageInfo

func (m *ConfigOptionsRequest) GetItem() *ConfigOptions {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *ConfigOptionsRequest) GetModification() *ConfigModification {
	if m != nil {
		return m.Modification
	}
	return nil
}

type ConfigOptionsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigOptionsResponse) Reset()         { *m = ConfigOptionsResponse{} }
func (m *ConfigOptionsResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigOptionsResponse) ProtoMessage()    {}
func (*ConfigOptionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{18}
}

func (m *ConfigOptionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigOptionsResponse.Unmarshal(m, b)
}
func (m *ConfigOptionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigOptionsResponse.Marshal(b, m, deterministic)
}
func (m *ConfigOptionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigOptionsResponse.Merge(m, src)
}
func (m *ConfigOptionsResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigOptionsResponse.Size(m)
}
func (m *ConfigOptionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigOptionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigOptionsResponse proto.InternalMessageInfo

type AccountRequest struct {
	Item                 *v1.Account         `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Modification         *ConfigModification `protobuf:"bytes,2,opt,name=modification,proto3" json:"modification,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AccountRequest) Reset()         { *m = AccountRequest{} }
func (m *AccountRequest) String() string { return proto.CompactTextString(m) }
func (*AccountRequest) ProtoMessage()    {}
func (*AccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{19}
}

func (m *AccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountRequest.Unmarshal(m, b)
}
func (m *AccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountRequest.Marshal(b, m, deterministic)
}
func (m *AccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountRequest.Merge(m, src)
}
func (m *AccountRequest) XXX_Size() int {
	return xxx_messageInfo_AccountRequest.Size(m)
}
func (m *AccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountRequest proto.InternalMessageInfo

func (m *AccountRequest) GetItem() *v1.Account {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *AccountRequest) GetModification() *ConfigModification {
	if m != nil {
		return m.Modification
	}
	return nil
}

type AccountResponse struct {
	Account              *v1.Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AccountResponse) Reset()         { *m = AccountResponse{} }
func (m *AccountResponse) String() string { return proto.CompactTextString(m) }
func (*AccountResponse) ProtoMessage()    {}
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{20}
}

func (m *AccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountResponse.Unmarshal(m, b)
}
func (m *AccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountResponse.Marshal(b, m, deterministic)
}
func (m *AccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountResponse.Merge(m, src)
}
func (m *AccountResponse) XXX_Size() int {
	return xxx_messageInfo_AccountResponse.Size(m)
}
func (m *AccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountResponse proto.InternalMessageInfo

func (m *AccountResponse) GetAccount() *v1.Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type AccountSubjectRequest struct {
	Item                 *v1.ConnectedAccount `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Modification         *ConfigModification  `protobuf:"bytes,2,opt,name=modification,proto3" json:"modification,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AccountSubjectRequest) Reset()         { *m = AccountSubjectRequest{} }
func (m *AccountSubjectRequest) String() string { return proto.CompactTextString(m) }
func (*AccountSubjectRequest) ProtoMessage()    {}
func (*AccountSubjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{21}
}

func (m *AccountSubjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountSubjectRequest.Unmarshal(m, b)
}
func (m *AccountSubjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountSubjectRequest.Marshal(b, m, deterministic)
}
func (m *AccountSubjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountSubjectRequest.Merge(m, src)
}
func (m *AccountSubjectRequest) XXX_Size() int {
	return xxx_messageInfo_AccountSubjectRequest.Size(m)
}
func (m *AccountSubjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountSubjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountSubjectRequest proto.InternalMessageInfo

func (m *AccountSubjectRequest) GetItem() *v1.ConnectedAccount {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *AccountSubjectRequest) GetModification() *ConfigModification {
	if m != nil {
		return m.Modification
	}
	return nil
}

type AccountSubjectResponse struct {
	Item                 *v1.ConnectedAccount `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AccountSubjectResponse) Reset()         { *m = AccountSubjectResponse{} }
func (m *AccountSubjectResponse) String() string { return proto.CompactTextString(m) }
func (*AccountSubjectResponse) ProtoMessage()    {}
func (*AccountSubjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{22}
}

func (m *AccountSubjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountSubjectResponse.Unmarshal(m, b)
}
func (m *AccountSubjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountSubjectResponse.Marshal(b, m, deterministic)
}
func (m *AccountSubjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountSubjectResponse.Merge(m, src)
}
func (m *AccountSubjectResponse) XXX_Size() int {
	return xxx_messageInfo_AccountSubjectResponse.Size(m)
}
func (m *AccountSubjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountSubjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountSubjectResponse proto.InternalMessageInfo

func (m *AccountSubjectResponse) GetItem() *v1.ConnectedAccount {
	if m != nil {
		return m.Item
	}
	return nil
}

type SubjectClaimsRequest struct {
	Modification         *ConfigModification `protobuf:"bytes,1,opt,name=modification,proto3" json:"modification,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SubjectClaimsRequest) Reset()         { *m = SubjectClaimsRequest{} }
func (m *SubjectClaimsRequest) String() string { return proto.CompactTextString(m) }
func (*SubjectClaimsRequest) ProtoMessage()    {}
func (*SubjectClaimsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{23}
}

func (m *SubjectClaimsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubjectClaimsRequest.Unmarshal(m, b)
}
func (m *SubjectClaimsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubjectClaimsRequest.Marshal(b, m, deterministic)
}
func (m *SubjectClaimsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubjectClaimsRequest.Merge(m, src)
}
func (m *SubjectClaimsRequest) XXX_Size() int {
	return xxx_messageInfo_SubjectClaimsRequest.Size(m)
}
func (m *SubjectClaimsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubjectClaimsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubjectClaimsRequest proto.InternalMessageInfo

func (m *SubjectClaimsRequest) GetModification() *ConfigModification {
	if m != nil {
		return m.Modification
	}
	return nil
}

type SubjectClaimsResponse struct {
	Assertions           []*v1.Assertion `protobuf:"bytes,1,rep,name=assertions,proto3" json:"assertions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SubjectClaimsResponse) Reset()         { *m = SubjectClaimsResponse{} }
func (m *SubjectClaimsResponse) String() string { return proto.CompactTextString(m) }
func (*SubjectClaimsResponse) ProtoMessage()    {}
func (*SubjectClaimsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{24}
}

func (m *SubjectClaimsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubjectClaimsResponse.Unmarshal(m, b)
}
func (m *SubjectClaimsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubjectClaimsResponse.Marshal(b, m, deterministic)
}
func (m *SubjectClaimsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubjectClaimsResponse.Merge(m, src)
}
func (m *SubjectClaimsResponse) XXX_Size() int {
	return xxx_messageInfo_SubjectClaimsResponse.Size(m)
}
func (m *SubjectClaimsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubjectClaimsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubjectClaimsResponse proto.InternalMessageInfo

func (m *SubjectClaimsResponse) GetAssertions() []*v1.Assertion {
	if m != nil {
		return m.Assertions
	}
	return nil
}

type TokenMetadata struct {
	TokenType            string   `protobuf:"bytes,1,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	IssuedAt             int64    `protobuf:"varint,2,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	Scope                string   `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	IdentityProvider     string   `protobuf:"bytes,4,opt,name=identity_provider,json=identityProvider,proto3" json:"identity_provider,omitempty"`
	Subject              string   `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	Nonce                string   `protobuf:"bytes,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenMetadata) Reset()         { *m = TokenMetadata{} }
func (m *TokenMetadata) String() string { return proto.CompactTextString(m) }
func (*TokenMetadata) ProtoMessage()    {}
func (*TokenMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{25}
}

func (m *TokenMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenMetadata.Unmarshal(m, b)
}
func (m *TokenMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenMetadata.Marshal(b, m, deterministic)
}
func (m *TokenMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenMetadata.Merge(m, src)
}
func (m *TokenMetadata) XXX_Size() int {
	return xxx_messageInfo_TokenMetadata.Size(m)
}
func (m *TokenMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_TokenMetadata proto.InternalMessageInfo

func (m *TokenMetadata) GetTokenType() string {
	if m != nil {
		return m.TokenType
	}
	return ""
}

func (m *TokenMetadata) GetIssuedAt() int64 {
	if m != nil {
		return m.IssuedAt
	}
	return 0
}

func (m *TokenMetadata) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *TokenMetadata) GetIdentityProvider() string {
	if m != nil {
		return m.IdentityProvider
	}
	return ""
}

func (m *TokenMetadata) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *TokenMetadata) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

type TokenMetadataRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenMetadataRequest) Reset()         { *m = TokenMetadataRequest{} }
func (m *TokenMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*TokenMetadataRequest) ProtoMessage()    {}
func (*TokenMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{26}
}

func (m *TokenMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenMetadataRequest.Unmarshal(m, b)
}
func (m *TokenMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenMetadataRequest.Marshal(b, m, deterministic)
}
func (m *TokenMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenMetadataRequest.Merge(m, src)
}
func (m *TokenMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_TokenMetadataRequest.Size(m)
}
func (m *TokenMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TokenMetadataRequest proto.InternalMessageInfo

type TokenMetadataResponse struct {
	TokenMetadata        *TokenMetadata `protobuf:"bytes,1,opt,name=token_metadata,json=tokenMetadata,proto3" json:"token_metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TokenMetadataResponse) Reset()         { *m = TokenMetadataResponse{} }
func (m *TokenMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*TokenMetadataResponse) ProtoMessage()    {}
func (*TokenMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{27}
}

func (m *TokenMetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenMetadataResponse.Unmarshal(m, b)
}
func (m *TokenMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenMetadataResponse.Marshal(b, m, deterministic)
}
func (m *TokenMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenMetadataResponse.Merge(m, src)
}
func (m *TokenMetadataResponse) XXX_Size() int {
	return xxx_messageInfo_TokenMetadataResponse.Size(m)
}
func (m *TokenMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TokenMetadataResponse proto.InternalMessageInfo

func (m *TokenMetadataResponse) GetTokenMetadata() *TokenMetadata {
	if m != nil {
		return m.TokenMetadata
	}
	return nil
}

type TokensMetadataRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokensMetadataRequest) Reset()         { *m = TokensMetadataRequest{} }
func (m *TokensMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*TokensMetadataRequest) ProtoMessage()    {}
func (*TokensMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{28}
}

func (m *TokensMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokensMetadataRequest.Unmarshal(m, b)
}
func (m *TokensMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokensMetadataRequest.Marshal(b, m, deterministic)
}
func (m *TokensMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokensMetadataRequest.Merge(m, src)
}
func (m *TokensMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_TokensMetadataRequest.Size(m)
}
func (m *TokensMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TokensMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TokensMetadataRequest proto.InternalMessageInfo

type TokensMetadataResponse struct {
	TokensMetadata       map[string]*TokenMetadata `protobuf:"bytes,1,rep,name=tokens_metadata,json=tokensMetadata,proto3" json:"tokens_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *TokensMetadataResponse) Reset()         { *m = TokensMetadataResponse{} }
func (m *TokensMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*TokensMetadataResponse) ProtoMessage()    {}
func (*TokensMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{29}
}

func (m *TokensMetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokensMetadataResponse.Unmarshal(m, b)
}
func (m *TokensMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokensMetadataResponse.Marshal(b, m, deterministic)
}
func (m *TokensMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokensMetadataResponse.Merge(m, src)
}
func (m *TokensMetadataResponse) XXX_Size() int {
	return xxx_messageInfo_TokensMetadataResponse.Size(m)
}
func (m *TokensMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TokensMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TokensMetadataResponse proto.InternalMessageInfo

func (m *TokensMetadataResponse) GetTokensMetadata() map[string]*TokenMetadata {
	if m != nil {
		return m.TokensMetadata
	}
	return nil
}

type RevocationRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevocationRequest) Reset()         { *m = RevocationRequest{} }
func (m *RevocationRequest) String() string { return proto.CompactTextString(m) }
func (*RevocationRequest) ProtoMessage()    {}
func (*RevocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{30}
}

func (m *RevocationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevocationRequest.Unmarshal(m, b)
}
func (m *RevocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevocationRequest.Marshal(b, m, deterministic)
}
func (m *RevocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevocationRequest.Merge(m, src)
}
func (m *RevocationRequest) XXX_Size() int {
	return xxx_messageInfo_RevocationRequest.Size(m)
}
func (m *RevocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RevocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RevocationRequest proto.InternalMessageInfo

func (m *RevocationRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LoginPageProviders struct {
	Idps                 map[string]*LoginPageProviders_ProviderEntry `protobuf:"bytes,1,rep,name=idps,proto3" json:"idps,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Personas             map[string]*LoginPageProviders_ProviderEntry `protobuf:"bytes,2,rep,name=personas,proto3" json:"personas,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *LoginPageProviders) Reset()         { *m = LoginPageProviders{} }
func (m *LoginPageProviders) String() string { return proto.CompactTextString(m) }
func (*LoginPageProviders) ProtoMessage()    {}
func (*LoginPageProviders) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{31}
}

func (m *LoginPageProviders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginPageProviders.Unmarshal(m, b)
}
func (m *LoginPageProviders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginPageProviders.Marshal(b, m, deterministic)
}
func (m *LoginPageProviders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginPageProviders.Merge(m, src)
}
func (m *LoginPageProviders) XXX_Size() int {
	return xxx_messageInfo_LoginPageProviders.Size(m)
}
func (m *LoginPageProviders) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginPageProviders.DiscardUnknown(m)
}

var xxx_messageInfo_LoginPageProviders proto.InternalMessageInfo

func (m *LoginPageProviders) GetIdps() map[string]*LoginPageProviders_ProviderEntry {
	if m != nil {
		return m.Idps
	}
	return nil
}

func (m *LoginPageProviders) GetPersonas() map[string]*LoginPageProviders_ProviderEntry {
	if m != nil {
		return m.Personas
	}
	return nil
}

type LoginPageProviders_ProviderEntry struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url                  string            `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Ui                   map[string]string `protobuf:"bytes,3,rep,name=ui,proto3" json:"ui,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LoginPageProviders_ProviderEntry) Reset()         { *m = LoginPageProviders_ProviderEntry{} }
func (m *LoginPageProviders_ProviderEntry) String() string { return proto.CompactTextString(m) }
func (*LoginPageProviders_ProviderEntry) ProtoMessage()    {}
func (*LoginPageProviders_ProviderEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{31, 0}
}

func (m *LoginPageProviders_ProviderEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginPageProviders_ProviderEntry.Unmarshal(m, b)
}
func (m *LoginPageProviders_ProviderEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginPageProviders_ProviderEntry.Marshal(b, m, deterministic)
}
func (m *LoginPageProviders_ProviderEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginPageProviders_ProviderEntry.Merge(m, src)
}
func (m *LoginPageProviders_ProviderEntry) XXX_Size() int {
	return xxx_messageInfo_LoginPageProviders_ProviderEntry.Size(m)
}
func (m *LoginPageProviders_ProviderEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginPageProviders_ProviderEntry.DiscardUnknown(m)
}

var xxx_messageInfo_LoginPageProviders_ProviderEntry proto.InternalMessageInfo

func (m *LoginPageProviders_ProviderEntry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginPageProviders_ProviderEntry) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *LoginPageProviders_ProviderEntry) GetUi() map[string]string {
	if m != nil {
		return m.Ui
	}
	return nil
}

type GetPersonasResponse struct {
	Personas             map[string]*GetPersonasResponse_Meta `protobuf:"bytes,1,rep,name=personas,proto3" json:"personas,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *GetPersonasResponse) Reset()         { *m = GetPersonasResponse{} }
func (m *GetPersonasResponse) String() string { return proto.CompactTextString(m) }
func (*GetPersonasResponse) ProtoMessage()    {}
func (*GetPersonasResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{32}
}

func (m *GetPersonasResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPersonasResponse.Unmarshal(m, b)
}
func (m *GetPersonasResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPersonasResponse.Marshal(b, m, deterministic)
}
func (m *GetPersonasResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPersonasResponse.Merge(m, src)
}
func (m *GetPersonasResponse) XXX_Size() int {
	return xxx_messageInfo_GetPersonasResponse.Size(m)
}
func (m *GetPersonasResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPersonasResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPersonasResponse proto.InternalMessageInfo

func (m *GetPersonasResponse) GetPersonas() map[string]*GetPersonasResponse_Meta {
	if m != nil {
		return m.Personas
	}
	return nil
}

type GetPersonasResponse_Meta struct {
	ClaimNames           []string `protobuf:"bytes,1,rep,name=claim_names,json=claimNames,proto3" json:"claim_names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPersonasResponse_Meta) Reset()         { *m = GetPersonasResponse_Meta{} }
func (m *GetPersonasResponse_Meta) String() string { return proto.CompactTextString(m) }
func (*GetPersonasResponse_Meta) ProtoMessage()    {}
func (*GetPersonasResponse_Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_4034d8e2323af80a, []int{32, 0}
}

func (m *GetPersonasResponse_Meta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPersonasResponse_Meta.Unmarshal(m, b)
}
func (m *GetPersonasResponse_Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPersonasResponse_Meta.Marshal(b, m, deterministic)
}
func (m *GetPersonasResponse_Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPersonasResponse_Meta.Merge(m, src)
}
func (m *GetPersonasResponse_Meta) XXX_Size() int {
	return xxx_messageInfo_GetPersonasResponse_Meta.Size(m)
}
func (m *GetPersonasResponse_Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPersonasResponse_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_GetPersonasResponse_Meta proto.InternalMessageInfo

func (m *GetPersonasResponse_Meta) GetClaimNames() []string {
	if m != nil {
		return m.ClaimNames
	}
	return nil
}

func init() {
	proto.RegisterType((*IcConfig)(nil), "ic.v1.IcConfig")
	proto.RegisterMapType((map[string]*v1.Client)(nil), "ic.v1.IcConfig.ClientsEntry")
	proto.RegisterMapType((map[string]*v1.IdentityProvider)(nil), "ic.v1.IcConfig.IdentityProvidersEntry")
	proto.RegisterMapType((map[string]string)(nil), "ic.v1.IcConfig.UiEntry")
	proto.RegisterType((*ConfigOptions)(nil), "ic.v1.ConfigOptions")
	proto.RegisterMapType((map[string]*v1.Descriptor)(nil), "ic.v1.ConfigOptions.ComputedDescriptorsEntry")
	proto.RegisterType((*IcSecrets)(nil), "ic.v1.IcSecrets")
	proto.RegisterMapType((map[string]string)(nil), "ic.v1.IcSecrets.ClientSecretsEntry")
	proto.RegisterMapType((map[string]string)(nil), "ic.v1.IcSecrets.IdProviderSecretsEntry")
	proto.RegisterMapType((map[string]*IcSecrets_TokenKeys)(nil), "ic.v1.IcSecrets.TokenKeysEntry")
	proto.RegisterType((*IcSecrets_TokenKeys)(nil), "ic.v1.IcSecrets.TokenKeys")
	proto.RegisterType((*ReadOnlyConfig)(nil), "ic.v1.ReadOnlyConfig")
	proto.RegisterType((*Realm)(nil), "ic.v1.Realm")
	proto.RegisterType((*ConfigModification)(nil), "ic.v1.ConfigModification")
	proto.RegisterType((*GetInfoRequest)(nil), "ic.v1.GetInfoRequest")
	proto.RegisterType((*GetInfoResponse)(nil), "ic.v1.GetInfoResponse")
	proto.RegisterMapType((map[string]string)(nil), "ic.v1.GetInfoResponse.UiEntry")
	proto.RegisterType((*RealmRequest)(nil), "ic.v1.RealmRequest")
	proto.RegisterType((*RealmResponse)(nil), "ic.v1.RealmResponse")
	proto.RegisterType((*GetIdentityProvidersRequest)(nil), "ic.v1.GetIdentityProvidersRequest")
	proto.RegisterType((*GetIdentityProvidersResponse)(nil), "ic.v1.GetIdentityProvidersResponse")
	proto.RegisterMapType((map[string]*v1.IdentityProvider)(nil), "ic.v1.GetIdentityProvidersResponse.IdentityProvidersEntry")
	proto.RegisterType((*GetTokenRequest)(nil), "ic.v1.GetTokenRequest")
	proto.RegisterType((*ConfigRequest)(nil), "ic.v1.ConfigRequest")
	proto.RegisterType((*ConfigResponse)(nil), "ic.v1.ConfigResponse")
	proto.RegisterType((*ConfigIdentityProviderRequest)(nil), "ic.v1.ConfigIdentityProviderRequest")
	proto.RegisterType((*ConfigIdProviderResponse)(nil), "ic.v1.ConfigIdProviderResponse")
	proto.RegisterType((*ConfigOptionsRequest)(nil), "ic.v1.ConfigOptionsRequest")
	proto.RegisterType((*ConfigOptionsResponse)(nil), "ic.v1.ConfigOptionsResponse")
	proto.RegisterType((*AccountRequest)(nil), "ic.v1.AccountRequest")
	proto.RegisterType((*AccountResponse)(nil), "ic.v1.AccountResponse")
	proto.RegisterType((*AccountSubjectRequest)(nil), "ic.v1.AccountSubjectRequest")
	proto.RegisterType((*AccountSubjectResponse)(nil), "ic.v1.AccountSubjectResponse")
	proto.RegisterType((*SubjectClaimsRequest)(nil), "ic.v1.SubjectClaimsRequest")
	proto.RegisterType((*SubjectClaimsResponse)(nil), "ic.v1.SubjectClaimsResponse")
	proto.RegisterType((*TokenMetadata)(nil), "ic.v1.TokenMetadata")
	proto.RegisterType((*TokenMetadataRequest)(nil), "ic.v1.TokenMetadataRequest")
	proto.RegisterType((*TokenMetadataResponse)(nil), "ic.v1.TokenMetadataResponse")
	proto.RegisterType((*TokensMetadataRequest)(nil), "ic.v1.TokensMetadataRequest")
	proto.RegisterType((*TokensMetadataResponse)(nil), "ic.v1.TokensMetadataResponse")
	proto.RegisterMapType((map[string]*TokenMetadata)(nil), "ic.v1.TokensMetadataResponse.TokensMetadataEntry")
	proto.RegisterType((*RevocationRequest)(nil), "ic.v1.RevocationRequest")
	proto.RegisterType((*LoginPageProviders)(nil), "ic.v1.LoginPageProviders")
	proto.RegisterMapType((map[string]*LoginPageProviders_ProviderEntry)(nil), "ic.v1.LoginPageProviders.IdpsEntry")
	proto.RegisterMapType((map[string]*LoginPageProviders_ProviderEntry)(nil), "ic.v1.LoginPageProviders.PersonasEntry")
	proto.RegisterType((*LoginPageProviders_ProviderEntry)(nil), "ic.v1.LoginPageProviders.ProviderEntry")
	proto.RegisterMapType((map[string]string)(nil), "ic.v1.LoginPageProviders.ProviderEntry.UiEntry")
	proto.RegisterType((*GetPersonasResponse)(nil), "ic.v1.GetPersonasResponse")
	proto.RegisterMapType((map[string]*GetPersonasResponse_Meta)(nil), "ic.v1.GetPersonasResponse.PersonasEntry")
	proto.RegisterType((*GetPersonasResponse_Meta)(nil), "ic.v1.GetPersonasResponse.Meta")
}

func init() { proto.RegisterFile("proto/ic/v1/ic_service.proto", fileDescriptor_4034d8e2323af80a) }

var fileDescriptor_4034d8e2323af80a = []byte{
	// 1654 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xdd, 0x72, 0xe4, 0x46,
	0x15, 0x2e, 0x79, 0xc6, 0x9e, 0x99, 0xe3, 0x9d, 0xb1, 0xa7, 0xed, 0xb5, 0x15, 0xc5, 0x66, 0x8d,
	0x42, 0xe1, 0x09, 0xc4, 0xe3, 0xd8, 0xa9, 0x10, 0x2a, 0x10, 0x42, 0x32, 0x86, 0x2d, 0xaf, 0xb3,
	0x59, 0xa3, 0xd8, 0x95, 0xd4, 0x16, 0x85, 0x90, 0xa5, 0xb6, 0xdd, 0xac, 0xa4, 0x16, 0xea, 0xd6,
	0x94, 0xe7, 0x8a, 0x1b, 0xae, 0x28, 0x1e, 0x05, 0x5e, 0x81, 0x37, 0xe0, 0x11, 0xb8, 0x80, 0x3b,
	0x5e, 0x80, 0x6b, 0xaa, 0x7f, 0x24, 0x4b, 0x1a, 0x39, 0x89, 0x53, 0xde, 0xbb, 0xe9, 0xf3, 0xf3,
	0x9d, 0xaf, 0x4f, 0x9f, 0xee, 0x73, 0x34, 0xb0, 0x95, 0xa4, 0x94, 0xd3, 0x7d, 0xe2, 0xef, 0x4f,
	0x0f, 0xf6, 0x89, 0xef, 0x32, 0x9c, 0x4e, 0x89, 0x8f, 0xc7, 0x52, 0x8c, 0x16, 0x89, 0x3f, 0x9e,
	0x1e, 0x58, 0xdb, 0xca, 0xc8, 0xa7, 0x51, 0x44, 0x63, 0x61, 0xe8, 0xf9, 0x3e, 0xcd, 0x62, 0xae,
	0xac, 0xac, 0xad, 0xba, 0x5a, 0xfd, 0xd2, 0xda, 0xef, 0xd7, 0xb5, 0xd4, 0xcb, 0xf8, 0xb5, 0x1f,
	0x12, 0x9c, 0x03, 0xd8, 0x7f, 0x6b, 0x43, 0xf7, 0xd8, 0x9f, 0xd0, 0xf8, 0x92, 0x5c, 0x21, 0x13,
	0x3a, 0x53, 0x9c, 0x32, 0x42, 0x63, 0xd3, 0xd8, 0x31, 0x46, 0x3d, 0x27, 0x5f, 0x22, 0x0b, 0xba,
	0x29, 0x9e, 0x12, 0xa9, 0x5a, 0xd8, 0x31, 0x46, 0x2d, 0xa7, 0x58, 0xa3, 0x27, 0xb0, 0x2c, 0x22,
	0x10, 0xee, 0x72, 0x12, 0x61, 0xb3, 0xb5, 0x63, 0x8c, 0x0c, 0x07, 0x94, 0xe8, 0x8c, 0x44, 0x18,
	0x9d, 0x03, 0x22, 0x01, 0x8e, 0x39, 0xe1, 0x33, 0x37, 0x49, 0xe9, 0x94, 0x04, 0x38, 0x65, 0x66,
	0x7b, 0xa7, 0x35, 0x5a, 0x3e, 0xfc, 0xe1, 0x58, 0xee, 0x73, 0x9c, 0x73, 0x18, 0x1f, 0x6b, 0xcb,
	0xd3, 0xdc, 0xf0, 0x57, 0x31, 0x4f, 0x67, 0xce, 0x90, 0xd4, 0xe5, 0xe8, 0x27, 0xd0, 0x51, 0x5b,
	0x61, 0xe6, 0xa2, 0xc4, 0xda, 0xaa, 0x63, 0x4d, 0x94, 0x5a, 0x21, 0xe4, 0xc6, 0x68, 0x0c, 0x1d,
	0x9a, 0x70, 0x42, 0x63, 0x66, 0x76, 0x76, 0x8c, 0xd1, 0xf2, 0xe1, 0xba, 0xf6, 0x53, 0x5e, 0x2f,
	0x94, 0xce, 0xc9, 0x8d, 0xd0, 0x2e, 0x2c, 0x64, 0xc4, 0xec, 0xca, 0x10, 0x9b, 0xf5, 0x10, 0xe7,
	0x44, 0xa1, 0x2f, 0x64, 0xc4, 0xfa, 0x1d, 0x6c, 0x34, 0xb3, 0x47, 0xab, 0xd0, 0x7a, 0x85, 0x67,
	0x3a, 0xa9, 0xe2, 0x27, 0x1a, 0xc3, 0xe2, 0xd4, 0x0b, 0x33, 0x2c, 0xb3, 0xb9, 0x7c, 0x68, 0x8e,
	0xf5, 0xc1, 0xd5, 0x01, 0x1c, 0x65, 0xf6, 0xe1, 0xc2, 0x4f, 0x0d, 0xeb, 0x19, 0x3c, 0x2a, 0xef,
	0xa8, 0x01, 0xf5, 0x07, 0x55, 0xd4, 0x41, 0x8e, 0xaa, 0xdc, 0xca, 0x58, 0xef, 0x43, 0x47, 0x53,
	0x6f, 0x80, 0x59, 0x2f, 0xc3, 0xf4, 0x4a, 0x6e, 0xf6, 0xbf, 0xda, 0xd0, 0xaf, 0xa4, 0x09, 0x1d,
	0xc2, 0x9a, 0x2e, 0x49, 0x37, 0xf6, 0x22, 0xec, 0x86, 0x38, 0xbe, 0xe2, 0xd7, 0x12, 0x6d, 0xf1,
	0xd3, 0x05, 0xd3, 0x70, 0x86, 0x5a, 0xfd, 0xb9, 0x17, 0xe1, 0xcf, 0xa4, 0x12, 0xbd, 0x07, 0x1b,
	0x29, 0xf6, 0x02, 0x97, 0xc6, 0xe1, 0xcc, 0x8d, 0x3c, 0xc6, 0x71, 0xea, 0xa6, 0xd8, 0x0b, 0x23,
	0x19, 0xb0, 0xeb, 0xac, 0x09, 0xed, 0x8b, 0x38, 0x9c, 0x3d, 0x97, 0x3a, 0x47, 0xa8, 0xd0, 0xc7,
	0x60, 0x05, 0xf8, 0xd2, 0xcb, 0x42, 0xee, 0x26, 0x1e, 0x63, 0x09, 0x4d, 0xb9, 0xcb, 0xe9, 0x2b,
	0x1c, 0xbb, 0x9c, 0x87, 0x66, 0x5b, 0x30, 0x95, 0xf1, 0x36, 0xb5, 0xd5, 0xa9, 0x36, 0x3a, 0x13,
	0x36, 0x67, 0x3c, 0x44, 0x1f, 0xc0, 0x46, 0xe4, 0xdd, 0x34, 0x39, 0x2f, 0x16, 0xce, 0x6b, 0x91,
	0x77, 0x33, 0xe7, 0x78, 0x00, 0x6b, 0xe2, 0xde, 0xb8, 0x3e, 0x0d, 0x70, 0xc9, 0x6b, 0xa9, 0xf0,
	0x5a, 0x15, 0xea, 0x09, 0x0d, 0x70, 0xe1, 0xf2, 0x0e, 0xac, 0x7a, 0xbe, 0x8f, 0x19, 0x2b, 0xd9,
	0x77, 0x0a, 0xfb, 0x81, 0xd2, 0x15, 0xd6, 0x63, 0x18, 0xa6, 0xf8, 0x32, 0xc5, 0xec, 0xba, 0x64,
	0xde, 0x2d, 0xcc, 0x57, 0xb4, 0xb2, 0xb0, 0xb7, 0xa1, 0xef, 0x87, 0x1e, 0x89, 0x84, 0x9d, 0xeb,
	0x7b, 0x89, 0xd9, 0x93, 0xe7, 0xb4, 0x2c, 0x85, 0x67, 0x3c, 0x9c, 0x78, 0x09, 0xfa, 0x0a, 0xd6,
	0x7d, 0x1a, 0x25, 0x19, 0xc7, 0x81, 0x1b, 0x60, 0xe6, 0xa7, 0x24, 0xe1, 0x34, 0x65, 0x26, 0xc8,
	0x3a, 0xde, 0x6b, 0x2a, 0xf9, 0xf1, 0x44, 0x3b, 0x1c, 0xdd, 0xda, 0xab, 0xea, 0x5e, 0x2e, 0x21,
	0x58, 0x2f, 0xc1, 0xbc, 0xcb, 0xb0, 0xa1, 0x96, 0x46, 0xd5, 0x92, 0x44, 0x79, 0x49, 0xde, 0xba,
	0x96, 0xeb, 0xeb, 0x7f, 0x6d, 0xe8, 0x1d, 0xfb, 0x5f, 0x60, 0x3f, 0xc5, 0x9c, 0xbd, 0xae, 0xf7,
	0xe8, 0x19, 0x0c, 0xd4, 0x5b, 0xe0, 0x32, 0x15, 0x48, 0xbf, 0x45, 0x6f, 0x15, 0x97, 0x5b, 0x13,
	0xd0, 0xf7, 0x46, 0xaf, 0x54, 0x2a, 0xfa, 0x7e, 0x59, 0x86, 0xbe, 0x84, 0x35, 0x12, 0x14, 0xaf,
	0x5a, 0x01, 0xa8, 0x1e, 0xa4, 0xdd, 0x39, 0xc0, 0xe3, 0x20, 0xbf, 0xd8, 0x15, 0xd0, 0x21, 0xa9,
	0xcb, 0xd1, 0x2f, 0x00, 0x54, 0x2d, 0xbc, 0xc2, 0x33, 0x66, 0x2e, 0x49, 0xbc, 0x27, 0x73, 0x78,
	0xb2, 0x24, 0x4e, 0xf0, 0x4c, 0xe3, 0xf4, 0x78, 0xbe, 0xb6, 0x7e, 0x09, 0x68, 0x9e, 0xfd, 0x7d,
	0xee, 0xba, 0x75, 0x24, 0x9e, 0xb3, 0x26, 0xba, 0xf7, 0x42, 0x39, 0x81, 0x5e, 0x41, 0x52, 0x1c,
	0x4d, 0x92, 0x92, 0xa9, 0xc7, 0xb1, 0x7b, 0x0b, 0x00, 0x5a, 0x74, 0x82, 0x67, 0x68, 0x1b, 0x20,
	0xc9, 0x2e, 0x42, 0xe2, 0x4b, 0xbd, 0x02, 0xeb, 0x29, 0xc9, 0x09, 0x9e, 0x59, 0x5f, 0xc1, 0xa0,
	0xba, 0xe3, 0x06, 0x2a, 0xef, 0x56, 0x0b, 0xce, 0xba, 0x3b, 0x67, 0xe5, 0xc2, 0x3b, 0x82, 0x81,
	0xa3, 0x1f, 0x1d, 0xdd, 0x0c, 0x37, 0xa1, 0x13, 0xe0, 0x1b, 0x37, 0x4b, 0x43, 0x8d, 0xbe, 0x14,
	0xe0, 0x9b, 0xf3, 0x34, 0x44, 0x6f, 0x40, 0x57, 0x28, 0xc4, 0x13, 0xa1, 0x19, 0x0a, 0xc3, 0x53,
	0x9a, 0x72, 0xbb, 0x03, 0x8b, 0xf2, 0xb1, 0xb2, 0x8f, 0x01, 0x29, 0x98, 0xe7, 0x34, 0x20, 0x97,
	0xc4, 0xf7, 0x78, 0xbd, 0x6a, 0x8d, 0x5a, 0xd5, 0x8a, 0x70, 0xe9, 0xcc, 0x4d, 0xb3, 0x58, 0x56,
	0x6c, 0xd7, 0x59, 0x0a, 0xd2, 0x99, 0x93, 0xc5, 0xf6, 0x2a, 0x0c, 0x9e, 0x62, 0x7e, 0x1c, 0x5f,
	0x52, 0x07, 0xff, 0x31, 0xc3, 0x8c, 0xdb, 0xff, 0x36, 0x60, 0xa5, 0x10, 0xb1, 0x84, 0xc6, 0x0c,
	0x23, 0x04, 0x6d, 0xf1, 0xfc, 0x6a, 0xaa, 0xf2, 0xb7, 0x08, 0xa7, 0xef, 0x0b, 0x33, 0x17, 0x76,
	0x5a, 0xa3, 0x9e, 0x53, 0xac, 0x45, 0xa2, 0x19, 0xf7, 0xd2, 0xd2, 0x1d, 0x69, 0x39, 0x3d, 0x29,
	0x91, 0x57, 0xc4, 0x84, 0x4e, 0x44, 0x83, 0x2c, 0xc4, 0xea, 0x6e, 0xf4, 0x9c, 0x7c, 0x89, 0xc6,
	0xb2, 0x1b, 0xaa, 0xfa, 0xfe, 0x9e, 0xce, 0x6d, 0x8d, 0x4c, 0xa5, 0x29, 0x7e, 0xc7, 0x46, 0xf3,
	0x2e, 0x3c, 0x92, 0x99, 0xd4, 0x7b, 0x46, 0x3b, 0xd0, 0x26, 0x1c, 0x47, 0xd2, 0x79, 0xf9, 0xf0,
	0x91, 0x0e, 0xac, 0x4c, 0xa4, 0xc6, 0x5e, 0x81, 0xbe, 0xf6, 0x50, 0x2c, 0xec, 0x6d, 0x78, 0x53,
	0x10, 0xab, 0x77, 0xe4, 0x3c, 0x8b, 0xff, 0x35, 0x60, 0xab, 0x59, 0xaf, 0x53, 0x4a, 0x1a, 0xc7,
	0x16, 0x43, 0xee, 0xfc, 0xc3, 0xd2, 0xce, 0xef, 0x02, 0xf8, 0xf6, 0xa3, 0xcc, 0xeb, 0x9e, 0x1c,
	0xec, 0xa1, 0x2c, 0x18, 0x59, 0xf8, 0xf9, 0xf6, 0x59, 0xde, 0xc8, 0xf3, 0x0c, 0xbf, 0x55, 0xc9,
	0xf0, 0x4a, 0x6d, 0xd0, 0x51, 0x49, 0x46, 0x1f, 0xc1, 0xa3, 0xa8, 0x54, 0xd1, 0x9a, 0xc3, 0x1b,
	0x95, 0x6e, 0x52, 0x2e, 0x79, 0xa7, 0x62, 0x2e, 0x6a, 0x39, 0x0f, 0xaa, 0x0f, 0xe9, 0xaf, 0x06,
	0x6c, 0x2b, 0xd1, 0x1c, 0x7f, 0xcd, 0xeb, 0x9d, 0x0a, 0xaf, 0xbb, 0xb7, 0xfb, 0x20, 0x04, 0x2d,
	0xd1, 0xdb, 0x14, 0x9b, 0x5b, 0x1e, 0x9a, 0xea, 0x9f, 0x60, 0xbd, 0x3a, 0x21, 0x6a, 0x82, 0xa3,
	0x0a, 0xc1, 0xe6, 0x61, 0xf2, 0x41, 0xc8, 0x6d, 0xc2, 0xe3, 0x1a, 0x01, 0xcd, 0x8c, 0xc3, 0xe0,
	0x13, 0x35, 0x64, 0xdd, 0x75, 0x98, 0x3a, 0x69, 0xb9, 0xd5, 0x83, 0xd0, 0xf9, 0x39, 0xac, 0x14,
	0x51, 0xf5, 0x95, 0x79, 0x1b, 0x3a, 0x7a, 0xda, 0xbb, 0x2b, 0x72, 0xae, 0xb7, 0xff, 0x6c, 0xc0,
	0x63, 0x2d, 0xfc, 0x22, 0xbb, 0xf8, 0x03, 0xf6, 0xf9, 0x37, 0x1c, 0xf8, 0x84, 0xc6, 0x31, 0xf6,
	0x39, 0x0e, 0x1e, 0x74, 0x13, 0xbf, 0x86, 0x8d, 0x3a, 0x0b, 0xbd, 0x97, 0x7b, 0xd1, 0xb0, 0xcf,
	0x61, 0x5d, 0x03, 0x4c, 0xc4, 0x10, 0x56, 0x14, 0x47, 0x9d, 0x9e, 0x71, 0x3f, 0x7a, 0xcf, 0xe0,
	0x71, 0x0d, 0x56, 0xb3, 0x3b, 0x00, 0xf0, 0x18, 0xc3, 0xa9, 0xfa, 0x8e, 0x51, 0x8f, 0xd2, 0xb0,
	0x48, 0x76, 0xae, 0x71, 0x4a, 0x46, 0xf6, 0x3f, 0x0c, 0xe8, 0xcb, 0x27, 0xe0, 0x39, 0xe6, 0x5e,
	0xe0, 0x71, 0x4f, 0x34, 0x01, 0x3d, 0x6f, 0xce, 0x92, 0xbc, 0x75, 0xa8, 0x11, 0xe2, 0x6c, 0x96,
	0x60, 0xf4, 0x26, 0xf4, 0x08, 0x63, 0x19, 0x0e, 0x5c, 0x8f, 0xe7, 0x53, 0x96, 0x12, 0x7c, 0xc2,
	0xc5, 0xd3, 0xcd, 0x7c, 0x9a, 0xa8, 0xde, 0xd1, 0x73, 0xd4, 0x02, 0xfd, 0x18, 0x86, 0x73, 0x6f,
	0xa6, 0x9a, 0xcd, 0x9d, 0xd5, 0xfa, 0xb3, 0x27, 0x9a, 0x0c, 0x53, 0x9b, 0x53, 0x13, 0xb8, 0x93,
	0x2f, 0x05, 0x78, 0x4c, 0x63, 0x1f, 0xab, 0x19, 0xdb, 0x51, 0x0b, 0x7b, 0x03, 0xd6, 0x2b, 0xfc,
	0xf3, 0xa7, 0xec, 0x0c, 0x1e, 0xd7, 0xe4, 0x3a, 0x49, 0x3f, 0x83, 0x81, 0xda, 0x5f, 0xa4, 0x35,
	0xb5, 0x3b, 0x5a, 0xf5, 0xea, 0xf3, 0xf2, 0x52, 0xdc, 0x36, 0xa9, 0x67, 0xf5, 0x70, 0xff, 0x34,
	0x60, 0xa3, 0xae, 0xd1, 0x01, 0x5f, 0xc2, 0x8a, 0x04, 0x61, 0xe5, 0x88, 0xe2, 0x68, 0x0e, 0xca,
	0x11, 0xe7, 0xfc, 0x6a, 0x62, 0xd5, 0x26, 0x14, 0xf5, 0x42, 0x68, 0x7d, 0x09, 0x6b, 0x0d, 0x66,
	0x0d, 0x0d, 0xe2, 0x47, 0xd5, 0x06, 0xd1, 0xbc, 0xd9, 0x52, 0x73, 0x78, 0x1b, 0x86, 0x0e, 0x9e,
	0x52, 0x5d, 0x7f, 0xba, 0x6e, 0xd7, 0x61, 0x51, 0xc6, 0xd7, 0xc0, 0x6a, 0x61, 0xff, 0xa5, 0x0d,
	0xe8, 0x33, 0x7a, 0x45, 0xe2, 0x53, 0xef, 0x0a, 0xdf, 0x7e, 0x89, 0x7f, 0x00, 0x6d, 0x12, 0x24,
	0x79, 0x19, 0xe6, 0x63, 0xf4, 0xbc, 0xe1, 0xf8, 0x38, 0x48, 0x74, 0x13, 0x94, 0x0e, 0x68, 0x02,
	0xdd, 0x04, 0xa7, 0x8c, 0xc6, 0x9e, 0x9a, 0x50, 0x6e, 0x47, 0xe6, 0x06, 0xe7, 0x53, 0x6d, 0xa9,
	0x00, 0x0a, 0x47, 0xeb, 0xef, 0x06, 0xf4, 0x73, 0x2b, 0x95, 0x93, 0xa6, 0x61, 0x68, 0x15, 0x5a,
	0x62, 0x94, 0x53, 0x83, 0x86, 0xf8, 0x89, 0x3e, 0x96, 0x93, 0x4c, 0x4b, 0x86, 0xdd, 0xff, 0x9a,
	0xb0, 0x65, 0xe8, 0x07, 0x18, 0x6d, 0xac, 0xdf, 0x43, 0xaf, 0xc8, 0x43, 0x83, 0xe3, 0x47, 0xd5,
	0xe3, 0xdb, 0xfd, 0x96, 0xcc, 0xca, 0x11, 0x02, 0xe8, 0x57, 0x92, 0xf5, 0x5a, 0xa2, 0xd8, 0xff,
	0x31, 0x60, 0xed, 0x29, 0xe6, 0x79, 0xa4, 0xe2, 0x12, 0x1c, 0x95, 0x0e, 0x55, 0x55, 0xc4, 0xe8,
	0x76, 0x5a, 0xaa, 0x5b, 0xdf, 0x79, 0xaa, 0xbb, 0xd0, 0x16, 0xc5, 0x2a, 0xbf, 0xe6, 0xe4, 0xb7,
	0xae, 0x38, 0x45, 0x05, 0xd8, 0x73, 0x40, 0x8a, 0x3e, 0x17, 0x12, 0xeb, 0xb7, 0xdf, 0xbc, 0xd9,
	0xf7, 0xab, 0x9b, 0x7d, 0xf2, 0x35, 0x74, 0x44, 0xcc, 0xd2, 0x26, 0x3f, 0xfd, 0xcd, 0xcb, 0x17,
	0x57, 0x84, 0x5f, 0x67, 0x17, 0xe2, 0x6d, 0xdd, 0x7f, 0x4a, 0xe9, 0x55, 0x88, 0x27, 0x21, 0xcd,
	0x82, 0xd3, 0xd0, 0xe3, 0x97, 0x34, 0x8d, 0xf6, 0xaf, 0xb1, 0x17, 0xf2, 0x6b, 0xdf, 0x4b, 0xf1,
	0xde, 0x25, 0x0e, 0x70, 0xea, 0x71, 0x1c, 0xec, 0xa9, 0x0f, 0xfc, 0x3d, 0xfd, 0x97, 0x1e, 0xdb,
	0x2f, 0xfd, 0xd5, 0x77, 0xb1, 0x24, 0x17, 0xef, 0xfd, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x17, 0xfe,
	0x3f, 0xa8, 0x00, 0x14, 0x00, 0x00,
}
