// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/common/v1/common.proto

// Package com defines messages shared between IC and DAM server.

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Assertion struct {
	Type                 string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Source               string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Value                string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	AssertedDuration     string                 `protobuf:"bytes,4,opt,name=asserted_duration,json=assertedDuration,proto3" json:"asserted_duration,omitempty"`
	ExpiresDuration      string                 `protobuf:"bytes,5,opt,name=expires_duration,json=expiresDuration,proto3" json:"expires_duration,omitempty"`
	Conditions           []*Assertion_Condition `protobuf:"bytes,6,rep,name=conditions,proto3" json:"conditions,omitempty"`
	By                   string                 `protobuf:"bytes,7,opt,name=by,proto3" json:"by,omitempty"`
	Asserted             int64                  `protobuf:"varint,8,opt,name=asserted,proto3" json:"asserted,omitempty"`
	Exp                  int64                  `protobuf:"varint,9,opt,name=exp,proto3" json:"exp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Assertion) Reset()         { *m = Assertion{} }
func (m *Assertion) String() string { return proto.CompactTextString(m) }
func (*Assertion) ProtoMessage()    {}
func (*Assertion) Descriptor() ([]byte, []int) {
	return fileDescriptor_988ca6f500b2cf3b, []int{0}
}

func (m *Assertion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Assertion.Unmarshal(m, b)
}
func (m *Assertion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Assertion.Marshal(b, m, deterministic)
}
func (m *Assertion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Assertion.Merge(m, src)
}
func (m *Assertion) XXX_Size() int {
	return xxx_messageInfo_Assertion.Size(m)
}
func (m *Assertion) XXX_DiscardUnknown() {
	xxx_messageInfo_Assertion.DiscardUnknown(m)
}

var xxx_messageInfo_Assertion proto.InternalMessageInfo

func (m *Assertion) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Assertion) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Assertion) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Assertion) GetAssertedDuration() string {
	if m != nil {
		return m.AssertedDuration
	}
	return ""
}

func (m *Assertion) GetExpiresDuration() string {
	if m != nil {
		return m.ExpiresDuration
	}
	return ""
}

func (m *Assertion) GetConditions() []*Assertion_Condition {
	if m != nil {
		return m.Conditions
	}
	return nil
}

func (m *Assertion) GetBy() string {
	if m != nil {
		return m.By
	}
	return ""
}

func (m *Assertion) GetAsserted() int64 {
	if m != nil {
		return m.Asserted
	}
	return 0
}

func (m *Assertion) GetExp() int64 {
	if m != nil {
		return m.Exp
	}
	return 0
}

type Assertion_ConditionClause struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	By                   string   `protobuf:"bytes,4,opt,name=by,proto3" json:"by,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Assertion_ConditionClause) Reset()         { *m = Assertion_ConditionClause{} }
func (m *Assertion_ConditionClause) String() string { return proto.CompactTextString(m) }
func (*Assertion_ConditionClause) ProtoMessage()    {}
func (*Assertion_ConditionClause) Descriptor() ([]byte, []int) {
	return fileDescriptor_988ca6f500b2cf3b, []int{0, 0}
}

func (m *Assertion_ConditionClause) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Assertion_ConditionClause.Unmarshal(m, b)
}
func (m *Assertion_ConditionClause) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Assertion_ConditionClause.Marshal(b, m, deterministic)
}
func (m *Assertion_ConditionClause) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Assertion_ConditionClause.Merge(m, src)
}
func (m *Assertion_ConditionClause) XXX_Size() int {
	return xxx_messageInfo_Assertion_ConditionClause.Size(m)
}
func (m *Assertion_ConditionClause) XXX_DiscardUnknown() {
	xxx_messageInfo_Assertion_ConditionClause.DiscardUnknown(m)
}

var xxx_messageInfo_Assertion_ConditionClause proto.InternalMessageInfo

func (m *Assertion_ConditionClause) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Assertion_ConditionClause) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Assertion_ConditionClause) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Assertion_ConditionClause) GetBy() string {
	if m != nil {
		return m.By
	}
	return ""
}

type Assertion_Condition struct {
	Clauses              []*Assertion_ConditionClause `protobuf:"bytes,1,rep,name=clauses,proto3" json:"clauses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *Assertion_Condition) Reset()         { *m = Assertion_Condition{} }
func (m *Assertion_Condition) String() string { return proto.CompactTextString(m) }
func (*Assertion_Condition) ProtoMessage()    {}
func (*Assertion_Condition) Descriptor() ([]byte, []int) {
	return fileDescriptor_988ca6f500b2cf3b, []int{0, 1}
}

func (m *Assertion_Condition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Assertion_Condition.Unmarshal(m, b)
}
func (m *Assertion_Condition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Assertion_Condition.Marshal(b, m, deterministic)
}
func (m *Assertion_Condition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Assertion_Condition.Merge(m, src)
}
func (m *Assertion_Condition) XXX_Size() int {
	return xxx_messageInfo_Assertion_Condition.Size(m)
}
func (m *Assertion_Condition) XXX_DiscardUnknown() {
	xxx_messageInfo_Assertion_Condition.DiscardUnknown(m)
}

var xxx_messageInfo_Assertion_Condition proto.InternalMessageInfo

func (m *Assertion_Condition) GetClauses() []*Assertion_ConditionClause {
	if m != nil {
		return m.Clauses
	}
	return nil
}

type Passport struct {
	StandardClaims         map[string]string `protobuf:"bytes,1,rep,name=standard_claims,json=standardClaims,proto3" json:"standard_claims,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Ga4GhAssertions        []*Assertion      `protobuf:"bytes,2,rep,name=ga4gh_assertions,json=ga4ghAssertions,proto3" json:"ga4gh_assertions,omitempty"`
	InternalEncryptedVisas [][]byte          `protobuf:"bytes,11,rep,name=internal_encrypted_visas,json=internalEncryptedVisas,proto3" json:"internal_encrypted_visas,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}          `json:"-"`
	XXX_unrecognized       []byte            `json:"-"`
	XXX_sizecache          int32             `json:"-"`
}

func (m *Passport) Reset()         { *m = Passport{} }
func (m *Passport) String() string { return proto.CompactTextString(m) }
func (*Passport) ProtoMessage()    {}
func (*Passport) Descriptor() ([]byte, []int) {
	return fileDescriptor_988ca6f500b2cf3b, []int{1}
}

func (m *Passport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Passport.Unmarshal(m, b)
}
func (m *Passport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Passport.Marshal(b, m, deterministic)
}
func (m *Passport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Passport.Merge(m, src)
}
func (m *Passport) XXX_Size() int {
	return xxx_messageInfo_Passport.Size(m)
}
func (m *Passport) XXX_DiscardUnknown() {
	xxx_messageInfo_Passport.DiscardUnknown(m)
}

var xxx_messageInfo_Passport proto.InternalMessageInfo

func (m *Passport) GetStandardClaims() map[string]string {
	if m != nil {
		return m.StandardClaims
	}
	return nil
}

func (m *Passport) GetGa4GhAssertions() []*Assertion {
	if m != nil {
		return m.Ga4GhAssertions
	}
	return nil
}

func (m *Passport) GetInternalEncryptedVisas() [][]byte {
	if m != nil {
		return m.InternalEncryptedVisas
	}
	return nil
}

type TestPersona struct {
	Passport             *Passport         `protobuf:"bytes,1,opt,name=passport,proto3" json:"passport,omitempty"`
	Access               []string          `protobuf:"bytes,2,rep,name=access,proto3" json:"access,omitempty"`
	Ui                   map[string]string `protobuf:"bytes,3,rep,name=ui,proto3" json:"ui,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TestPersona) Reset()         { *m = TestPersona{} }
func (m *TestPersona) String() string { return proto.CompactTextString(m) }
func (*TestPersona) ProtoMessage()    {}
func (*TestPersona) Descriptor() ([]byte, []int) {
	return fileDescriptor_988ca6f500b2cf3b, []int{2}
}

func (m *TestPersona) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestPersona.Unmarshal(m, b)
}
func (m *TestPersona) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestPersona.Marshal(b, m, deterministic)
}
func (m *TestPersona) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestPersona.Merge(m, src)
}
func (m *TestPersona) XXX_Size() int {
	return xxx_messageInfo_TestPersona.Size(m)
}
func (m *TestPersona) XXX_DiscardUnknown() {
	xxx_messageInfo_TestPersona.DiscardUnknown(m)
}

var xxx_messageInfo_TestPersona proto.InternalMessageInfo

func (m *TestPersona) GetPassport() *Passport {
	if m != nil {
		return m.Passport
	}
	return nil
}

func (m *TestPersona) GetAccess() []string {
	if m != nil {
		return m.Access
	}
	return nil
}

func (m *TestPersona) GetUi() map[string]string {
	if m != nil {
		return m.Ui
	}
	return nil
}

type Permissions struct {
	Version              string                                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Revision             int64                                  `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	CommitTime           float64                                `protobuf:"fixed64,3,opt,name=commit_time,json=commitTime,proto3" json:"commit_time,omitempty"`
	Users                map[string]*Permissions_PermissionUser `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *Permissions) Reset()         { *m = Permissions{} }
func (m *Permissions) String() string { return proto.CompactTextString(m) }
func (*Permissions) ProtoMessage()    {}
func (*Permissions) Descriptor() ([]byte, []int) {
	return fileDescriptor_988ca6f500b2cf3b, []int{3}
}

func (m *Permissions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Permissions.Unmarshal(m, b)
}
func (m *Permissions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Permissions.Marshal(b, m, deterministic)
}
func (m *Permissions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Permissions.Merge(m, src)
}
func (m *Permissions) XXX_Size() int {
	return xxx_messageInfo_Permissions.Size(m)
}
func (m *Permissions) XXX_DiscardUnknown() {
	xxx_messageInfo_Permissions.DiscardUnknown(m)
}

var xxx_messageInfo_Permissions proto.InternalMessageInfo

func (m *Permissions) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Permissions) GetRevision() int64 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *Permissions) GetCommitTime() float64 {
	if m != nil {
		return m.CommitTime
	}
	return 0
}

func (m *Permissions) GetUsers() map[string]*Permissions_PermissionUser {
	if m != nil {
		return m.Users
	}
	return nil
}

type Permissions_PermissionUser struct {
	Roles                map[string]int64 `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Tags                 []string         `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Permissions_PermissionUser) Reset()         { *m = Permissions_PermissionUser{} }
func (m *Permissions_PermissionUser) String() string { return proto.CompactTextString(m) }
func (*Permissions_PermissionUser) ProtoMessage()    {}
func (*Permissions_PermissionUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_988ca6f500b2cf3b, []int{3, 0}
}

func (m *Permissions_PermissionUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Permissions_PermissionUser.Unmarshal(m, b)
}
func (m *Permissions_PermissionUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Permissions_PermissionUser.Marshal(b, m, deterministic)
}
func (m *Permissions_PermissionUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Permissions_PermissionUser.Merge(m, src)
}
func (m *Permissions_PermissionUser) XXX_Size() int {
	return xxx_messageInfo_Permissions_PermissionUser.Size(m)
}
func (m *Permissions_PermissionUser) XXX_DiscardUnknown() {
	xxx_messageInfo_Permissions_PermissionUser.DiscardUnknown(m)
}

var xxx_messageInfo_Permissions_PermissionUser proto.InternalMessageInfo

func (m *Permissions_PermissionUser) GetRoles() map[string]int64 {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *Permissions_PermissionUser) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type AccountTag struct {
	Category             string            `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Ui                   map[string]string `protobuf:"bytes,3,rep,name=ui,proto3" json:"ui,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AccountTag) Reset()         { *m = AccountTag{} }
func (m *AccountTag) String() string { return proto.CompactTextString(m) }
func (*AccountTag) ProtoMessage()    {}
func (*AccountTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_988ca6f500b2cf3b, []int{4}
}

func (m *AccountTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountTag.Unmarshal(m, b)
}
func (m *AccountTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountTag.Marshal(b, m, deterministic)
}
func (m *AccountTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountTag.Merge(m, src)
}
func (m *AccountTag) XXX_Size() int {
	return xxx_messageInfo_AccountTag.Size(m)
}
func (m *AccountTag) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountTag.DiscardUnknown(m)
}

var xxx_messageInfo_AccountTag proto.InternalMessageInfo

func (m *AccountTag) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *AccountTag) GetUi() map[string]string {
	if m != nil {
		return m.Ui
	}
	return nil
}

// LoginState records states for login and login callback.
type LoginState struct {
	IdpName              string   `protobuf:"bytes,1,opt,name=idp_name,json=idpName,proto3" json:"idp_name,omitempty"`
	Realm                string   `protobuf:"bytes,2,opt,name=realm,proto3" json:"realm,omitempty"`
	ClientId             string   `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Scope                string   `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	Redirect             string   `protobuf:"bytes,5,opt,name=redirect,proto3" json:"redirect,omitempty"`
	State                string   `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	Nonce                string   `protobuf:"bytes,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginState) Reset()         { *m = LoginState{} }
func (m *LoginState) String() string { return proto.CompactTextString(m) }
func (*LoginState) ProtoMessage()    {}
func (*LoginState) Descriptor() ([]byte, []int) {
	return fileDescriptor_988ca6f500b2cf3b, []int{5}
}

func (m *LoginState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginState.Unmarshal(m, b)
}
func (m *LoginState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginState.Marshal(b, m, deterministic)
}
func (m *LoginState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginState.Merge(m, src)
}
func (m *LoginState) XXX_Size() int {
	return xxx_messageInfo_LoginState.Size(m)
}
func (m *LoginState) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginState.DiscardUnknown(m)
}

var xxx_messageInfo_LoginState proto.InternalMessageInfo

func (m *LoginState) GetIdpName() string {
	if m != nil {
		return m.IdpName
	}
	return ""
}

func (m *LoginState) GetRealm() string {
	if m != nil {
		return m.Realm
	}
	return ""
}

func (m *LoginState) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *LoginState) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *LoginState) GetRedirect() string {
	if m != nil {
		return m.Redirect
	}
	return ""
}

func (m *LoginState) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *LoginState) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

// AuthTokenState records states for create auth token.
type AuthTokenState struct {
	Redirect             string   `protobuf:"bytes,1,opt,name=redirect,proto3" json:"redirect,omitempty"`
	Subject              string   `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Scope                string   `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	Provider             string   `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	Realm                string   `protobuf:"bytes,5,opt,name=realm,proto3" json:"realm,omitempty"`
	State                string   `protobuf:"bytes,8,opt,name=state,proto3" json:"state,omitempty"`
	Nonce                string   `protobuf:"bytes,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	LoginHint            string   `protobuf:"bytes,7,opt,name=login_hint,json=loginHint,proto3" json:"login_hint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthTokenState) Reset()         { *m = AuthTokenState{} }
func (m *AuthTokenState) String() string { return proto.CompactTextString(m) }
func (*AuthTokenState) ProtoMessage()    {}
func (*AuthTokenState) Descriptor() ([]byte, []int) {
	return fileDescriptor_988ca6f500b2cf3b, []int{6}
}

func (m *AuthTokenState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthTokenState.Unmarshal(m, b)
}
func (m *AuthTokenState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthTokenState.Marshal(b, m, deterministic)
}
func (m *AuthTokenState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthTokenState.Merge(m, src)
}
func (m *AuthTokenState) XXX_Size() int {
	return xxx_messageInfo_AuthTokenState.Size(m)
}
func (m *AuthTokenState) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthTokenState.DiscardUnknown(m)
}

var xxx_messageInfo_AuthTokenState proto.InternalMessageInfo

func (m *AuthTokenState) GetRedirect() string {
	if m != nil {
		return m.Redirect
	}
	return ""
}

func (m *AuthTokenState) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *AuthTokenState) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *AuthTokenState) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *AuthTokenState) GetRealm() string {
	if m != nil {
		return m.Realm
	}
	return ""
}

func (m *AuthTokenState) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *AuthTokenState) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *AuthTokenState) GetLoginHint() string {
	if m != nil {
		return m.LoginHint
	}
	return ""
}

type TokenMetadata struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IssuedAt             string   `protobuf:"bytes,2,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	Expires              string   `protobuf:"bytes,3,opt,name=expires,proto3" json:"expires,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenMetadata) Reset()         { *m = TokenMetadata{} }
func (m *TokenMetadata) String() string { return proto.CompactTextString(m) }
func (*TokenMetadata) ProtoMessage()    {}
func (*TokenMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_988ca6f500b2cf3b, []int{7}
}

func (m *TokenMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenMetadata.Unmarshal(m, b)
}
func (m *TokenMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenMetadata.Marshal(b, m, deterministic)
}
func (m *TokenMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenMetadata.Merge(m, src)
}
func (m *TokenMetadata) XXX_Size() int {
	return xxx_messageInfo_TokenMetadata.Size(m)
}
func (m *TokenMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_TokenMetadata proto.InternalMessageInfo

func (m *TokenMetadata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TokenMetadata) GetIssuedAt() string {
	if m != nil {
		return m.IssuedAt
	}
	return ""
}

func (m *TokenMetadata) GetExpires() string {
	if m != nil {
		return m.Expires
	}
	return ""
}

type HistoryEntry struct {
	Revision             int64    `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	CommitTime           float64  `protobuf:"fixed64,3,opt,name=commit_time,json=commitTime,proto3" json:"commit_time,omitempty"`
	Path                 string   `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Query                string   `protobuf:"bytes,5,opt,name=query,proto3" json:"query,omitempty"`
	Desc                 string   `protobuf:"bytes,6,opt,name=desc,proto3" json:"desc,omitempty"`
	Method               string   `protobuf:"bytes,7,opt,name=method,proto3" json:"method,omitempty"`
	ChangeType           string   `protobuf:"bytes,8,opt,name=change_type,json=changeType,proto3" json:"change_type,omitempty"`
	OriginalValue        string   `protobuf:"bytes,9,opt,name=original_value,json=originalValue,proto3" json:"original_value,omitempty"`
	ChangeRequest        string   `protobuf:"bytes,10,opt,name=change_request,json=changeRequest,proto3" json:"change_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HistoryEntry) Reset()         { *m = HistoryEntry{} }
func (m *HistoryEntry) String() string { return proto.CompactTextString(m) }
func (*HistoryEntry) ProtoMessage()    {}
func (*HistoryEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_988ca6f500b2cf3b, []int{8}
}

func (m *HistoryEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistoryEntry.Unmarshal(m, b)
}
func (m *HistoryEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistoryEntry.Marshal(b, m, deterministic)
}
func (m *HistoryEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoryEntry.Merge(m, src)
}
func (m *HistoryEntry) XXX_Size() int {
	return xxx_messageInfo_HistoryEntry.Size(m)
}
func (m *HistoryEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoryEntry.DiscardUnknown(m)
}

var xxx_messageInfo_HistoryEntry proto.InternalMessageInfo

func (m *HistoryEntry) GetRevision() int64 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *HistoryEntry) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *HistoryEntry) GetCommitTime() float64 {
	if m != nil {
		return m.CommitTime
	}
	return 0
}

func (m *HistoryEntry) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *HistoryEntry) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *HistoryEntry) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *HistoryEntry) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *HistoryEntry) GetChangeType() string {
	if m != nil {
		return m.ChangeType
	}
	return ""
}

func (m *HistoryEntry) GetOriginalValue() string {
	if m != nil {
		return m.OriginalValue
	}
	return ""
}

func (m *HistoryEntry) GetChangeRequest() string {
	if m != nil {
		return m.ChangeRequest
	}
	return ""
}

type History struct {
	History              []*HistoryEntry `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	NextPageToken        string          `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *History) Reset()         { *m = History{} }
func (m *History) String() string { return proto.CompactTextString(m) }
func (*History) ProtoMessage()    {}
func (*History) Descriptor() ([]byte, []int) {
	return fileDescriptor_988ca6f500b2cf3b, []int{9}
}

func (m *History) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_History.Unmarshal(m, b)
}
func (m *History) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_History.Marshal(b, m, deterministic)
}
func (m *History) XXX_Merge(src proto.Message) {
	xxx_messageInfo_History.Merge(m, src)
}
func (m *History) XXX_Size() int {
	return xxx_messageInfo_History.Size(m)
}
func (m *History) XXX_DiscardUnknown() {
	xxx_messageInfo_History.DiscardUnknown(m)
}

var xxx_messageInfo_History proto.InternalMessageInfo

func (m *History) GetHistory() []*HistoryEntry {
	if m != nil {
		return m.History
	}
	return nil
}

func (m *History) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type OidcConfig struct {
	Issuer                 string   `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	JwksUri                string   `protobuf:"bytes,2,opt,name=jwks_uri,proto3" json:"jwks_uri,omitempty"`
	AuthEndpoint           string   `protobuf:"bytes,3,opt,name=auth_endpoint,json=authorization_endpoint,proto3" json:"auth_endpoint,omitempty"`
	ResponseTypesSupported []string `protobuf:"bytes,4,rep,name=response_types_supported,proto3" json:"response_types_supported,omitempty"`
	TokenEndpoint          string   `protobuf:"bytes,5,opt,name=token_endpoint,proto3" json:"token_endpoint,omitempty"`
	RevocationEndpoint     string   `protobuf:"bytes,8,opt,name=revocation_endpoint,proto3" json:"revocation_endpoint,omitempty"`
	UserinfoEndpoint       string   `protobuf:"bytes,6,opt,name=userinfo_endpoint,proto3" json:"userinfo_endpoint,omitempty"`
	ScopesSupported        []string `protobuf:"bytes,7,rep,name=scopes_supported,proto3" json:"scopes_supported,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *OidcConfig) Reset()         { *m = OidcConfig{} }
func (m *OidcConfig) String() string { return proto.CompactTextString(m) }
func (*OidcConfig) ProtoMessage()    {}
func (*OidcConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_988ca6f500b2cf3b, []int{10}
}

func (m *OidcConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OidcConfig.Unmarshal(m, b)
}
func (m *OidcConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OidcConfig.Marshal(b, m, deterministic)
}
func (m *OidcConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OidcConfig.Merge(m, src)
}
func (m *OidcConfig) XXX_Size() int {
	return xxx_messageInfo_OidcConfig.Size(m)
}
func (m *OidcConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_OidcConfig.DiscardUnknown(m)
}

var xxx_messageInfo_OidcConfig proto.InternalMessageInfo

func (m *OidcConfig) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *OidcConfig) GetJwksUri() string {
	if m != nil {
		return m.JwksUri
	}
	return ""
}

func (m *OidcConfig) GetAuthEndpoint() string {
	if m != nil {
		return m.AuthEndpoint
	}
	return ""
}

func (m *OidcConfig) GetResponseTypesSupported() []string {
	if m != nil {
		return m.ResponseTypesSupported
	}
	return nil
}

func (m *OidcConfig) GetTokenEndpoint() string {
	if m != nil {
		return m.TokenEndpoint
	}
	return ""
}

func (m *OidcConfig) GetRevocationEndpoint() string {
	if m != nil {
		return m.RevocationEndpoint
	}
	return ""
}

func (m *OidcConfig) GetUserinfoEndpoint() string {
	if m != nil {
		return m.UserinfoEndpoint
	}
	return ""
}

func (m *OidcConfig) GetScopesSupported() []string {
	if m != nil {
		return m.ScopesSupported
	}
	return nil
}

type OidcTokenResponse struct {
	AccessToken          string                  `protobuf:"bytes,1,opt,name=access_token,proto3" json:"access_token,omitempty"`
	TokenType            string                  `protobuf:"bytes,2,opt,name=token_type,proto3" json:"token_type,omitempty"`
	ExpiresIn            int32                   `protobuf:"varint,3,opt,name=expires_in,proto3" json:"expires_in,omitempty"`
	RefreshToken         string                  `protobuf:"bytes,4,opt,name=refresh_token,proto3" json:"refresh_token,omitempty"`
	IdToken              string                  `protobuf:"bytes,5,opt,name=id_token,proto3" json:"id_token,omitempty"`
	Scope                string                  `protobuf:"bytes,6,opt,name=scope,proto3" json:"scope,omitempty"`
	Uid                  string                  `protobuf:"bytes,7,opt,name=uid,proto3" json:"uid,omitempty"`
	Info                 *OidcTokenResponse_Info `protobuf:"bytes,8,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *OidcTokenResponse) Reset()         { *m = OidcTokenResponse{} }
func (m *OidcTokenResponse) String() string { return proto.CompactTextString(m) }
func (*OidcTokenResponse) ProtoMessage()    {}
func (*OidcTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_988ca6f500b2cf3b, []int{11}
}

func (m *OidcTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OidcTokenResponse.Unmarshal(m, b)
}
func (m *OidcTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OidcTokenResponse.Marshal(b, m, deterministic)
}
func (m *OidcTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OidcTokenResponse.Merge(m, src)
}
func (m *OidcTokenResponse) XXX_Size() int {
	return xxx_messageInfo_OidcTokenResponse.Size(m)
}
func (m *OidcTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OidcTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OidcTokenResponse proto.InternalMessageInfo

func (m *OidcTokenResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *OidcTokenResponse) GetTokenType() string {
	if m != nil {
		return m.TokenType
	}
	return ""
}

func (m *OidcTokenResponse) GetExpiresIn() int32 {
	if m != nil {
		return m.ExpiresIn
	}
	return 0
}

func (m *OidcTokenResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *OidcTokenResponse) GetIdToken() string {
	if m != nil {
		return m.IdToken
	}
	return ""
}

func (m *OidcTokenResponse) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *OidcTokenResponse) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OidcTokenResponse) GetInfo() *OidcTokenResponse_Info {
	if m != nil {
		return m.Info
	}
	return nil
}

type OidcTokenResponse_Info struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OidcTokenResponse_Info) Reset()         { *m = OidcTokenResponse_Info{} }
func (m *OidcTokenResponse_Info) String() string { return proto.CompactTextString(m) }
func (*OidcTokenResponse_Info) ProtoMessage()    {}
func (*OidcTokenResponse_Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_988ca6f500b2cf3b, []int{11, 0}
}

func (m *OidcTokenResponse_Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OidcTokenResponse_Info.Unmarshal(m, b)
}
func (m *OidcTokenResponse_Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OidcTokenResponse_Info.Marshal(b, m, deterministic)
}
func (m *OidcTokenResponse_Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OidcTokenResponse_Info.Merge(m, src)
}
func (m *OidcTokenResponse_Info) XXX_Size() int {
	return xxx_messageInfo_OidcTokenResponse_Info.Size(m)
}
func (m *OidcTokenResponse_Info) XXX_DiscardUnknown() {
	xxx_messageInfo_OidcTokenResponse_Info.DiscardUnknown(m)
}

var xxx_messageInfo_OidcTokenResponse_Info proto.InternalMessageInfo

func (m *OidcTokenResponse_Info) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OidcTokenResponse_Info) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*Assertion)(nil), "common.Assertion")
	proto.RegisterType((*Assertion_ConditionClause)(nil), "common.Assertion.ConditionClause")
	proto.RegisterType((*Assertion_Condition)(nil), "common.Assertion.Condition")
	proto.RegisterType((*Passport)(nil), "common.Passport")
	proto.RegisterMapType((map[string]string)(nil), "common.Passport.StandardClaimsEntry")
	proto.RegisterType((*TestPersona)(nil), "common.TestPersona")
	proto.RegisterMapType((map[string]string)(nil), "common.TestPersona.UiEntry")
	proto.RegisterType((*Permissions)(nil), "common.Permissions")
	proto.RegisterMapType((map[string]*Permissions_PermissionUser)(nil), "common.Permissions.UsersEntry")
	proto.RegisterType((*Permissions_PermissionUser)(nil), "common.Permissions.PermissionUser")
	proto.RegisterMapType((map[string]int64)(nil), "common.Permissions.PermissionUser.RolesEntry")
	proto.RegisterType((*AccountTag)(nil), "common.AccountTag")
	proto.RegisterMapType((map[string]string)(nil), "common.AccountTag.UiEntry")
	proto.RegisterType((*LoginState)(nil), "common.LoginState")
	proto.RegisterType((*AuthTokenState)(nil), "common.AuthTokenState")
	proto.RegisterType((*TokenMetadata)(nil), "common.TokenMetadata")
	proto.RegisterType((*HistoryEntry)(nil), "common.HistoryEntry")
	proto.RegisterType((*History)(nil), "common.History")
	proto.RegisterType((*OidcConfig)(nil), "common.OidcConfig")
	proto.RegisterType((*OidcTokenResponse)(nil), "common.OidcTokenResponse")
	proto.RegisterType((*OidcTokenResponse_Info)(nil), "common.OidcTokenResponse.Info")
}

func init() { proto.RegisterFile("proto/common/v1/common.proto", fileDescriptor_988ca6f500b2cf3b) }

var fileDescriptor_988ca6f500b2cf3b = []byte{
	// 1315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0x96, 0xff, 0x62, 0xfb, 0xb8, 0x71, 0x9c, 0x69, 0x55, 0x2d, 0x2e, 0x94, 0x60, 0xb5, 0x55,
	0x68, 0x1b, 0xa7, 0x84, 0x22, 0x45, 0x2d, 0x37, 0x21, 0x54, 0xb4, 0x12, 0x85, 0x68, 0x9b, 0xf6,
	0xa2, 0x42, 0x5a, 0x4d, 0x76, 0x4f, 0xec, 0x69, 0xd7, 0x3b, 0xdb, 0x99, 0x59, 0x53, 0xf3, 0x0a,
	0xdc, 0x72, 0xcd, 0x0d, 0xbc, 0x03, 0xbc, 0x01, 0x97, 0x5c, 0x73, 0xc5, 0xab, 0xa0, 0xf9, 0x5b,
	0x6f, 0x7e, 0x20, 0x42, 0xea, 0xdd, 0x7c, 0xdf, 0x9c, 0x39, 0x73, 0xce, 0x77, 0xce, 0x9e, 0xb1,
	0xe1, 0xfd, 0x5c, 0x70, 0xc5, 0xb7, 0x63, 0x3e, 0x9b, 0xf1, 0x6c, 0x7b, 0xfe, 0x89, 0x5b, 0x8d,
	0x0d, 0x4d, 0x56, 0x2c, 0x1a, 0xfd, 0xd9, 0x80, 0xee, 0x9e, 0x94, 0x28, 0x14, 0xe3, 0x19, 0x21,
	0xd0, 0x54, 0x8b, 0x1c, 0x83, 0xda, 0x46, 0x6d, 0xb3, 0x1b, 0x9a, 0x35, 0xb9, 0x0a, 0x2b, 0x92,
	0x17, 0x22, 0xc6, 0xa0, 0x6e, 0x58, 0x87, 0xc8, 0x15, 0x68, 0xcd, 0x69, 0x5a, 0x60, 0xd0, 0x30,
	0xb4, 0x05, 0xe4, 0x0e, 0xac, 0x53, 0xe3, 0x0e, 0x93, 0x28, 0x29, 0x04, 0xd5, 0x6e, 0x83, 0xa6,
	0xb1, 0x18, 0xf8, 0x8d, 0x2f, 0x1d, 0x4f, 0x3e, 0x86, 0x01, 0xbe, 0xcd, 0x99, 0x40, 0xb9, 0xb4,
	0x6d, 0x19, 0xdb, 0x35, 0xc7, 0x97, 0xa6, 0x0f, 0x01, 0x62, 0x9e, 0x25, 0x4c, 0x03, 0x19, 0xac,
	0x6c, 0x34, 0x36, 0x7b, 0x3b, 0xd7, 0xc6, 0x2e, 0xa5, 0x32, 0x81, 0xf1, 0xbe, 0xb7, 0x09, 0x2b,
	0xe6, 0xa4, 0x0f, 0xf5, 0xa3, 0x45, 0xd0, 0x36, 0x9e, 0xeb, 0x47, 0x0b, 0x32, 0x84, 0x8e, 0x8f,
	0x25, 0xe8, 0x6c, 0xd4, 0x36, 0x1b, 0x61, 0x89, 0xc9, 0x00, 0x1a, 0xf8, 0x36, 0x0f, 0xba, 0x86,
	0xd6, 0xcb, 0x61, 0x0c, 0x6b, 0xa5, 0xdb, 0xfd, 0x94, 0x16, 0x12, 0xdf, 0x81, 0x4e, 0x36, 0xa4,
	0xa6, 0x0f, 0x69, 0xf8, 0x18, 0xba, 0xe5, 0x25, 0xe4, 0x21, 0xb4, 0x63, 0x73, 0x91, 0x0c, 0x6a,
	0x26, 0xd3, 0x8f, 0xfe, 0x23, 0x53, 0x1b, 0x52, 0xe8, 0x4f, 0x8c, 0x7e, 0xaa, 0x43, 0xe7, 0x80,
	0x4a, 0x99, 0x73, 0xa1, 0xc8, 0x53, 0x58, 0x93, 0x8a, 0x66, 0x09, 0x15, 0x49, 0x14, 0xa7, 0x94,
	0xcd, 0xbc, 0xc7, 0x1b, 0xde, 0xa3, 0x37, 0x1d, 0x3f, 0x73, 0x76, 0xfb, 0xc6, 0xec, 0x51, 0xa6,
	0xc4, 0x22, 0xec, 0xcb, 0x13, 0x24, 0xf9, 0x1c, 0x06, 0x13, 0x7a, 0x7f, 0x32, 0x8d, 0xa8, 0x8f,
	0x43, 0x06, 0x75, 0xe3, 0x6f, 0xfd, 0x4c, 0x84, 0xe1, 0x9a, 0x31, 0x2d, 0xb1, 0x24, 0xbb, 0x10,
	0xb0, 0x4c, 0xa1, 0xc8, 0x68, 0x1a, 0x61, 0x16, 0x8b, 0x45, 0xae, 0xbb, 0x64, 0xce, 0x24, 0x95,
	0x41, 0x6f, 0xa3, 0xb1, 0x79, 0x29, 0xbc, 0xea, 0xf7, 0x1f, 0xf9, 0xed, 0x17, 0x7a, 0x77, 0xb8,
	0x07, 0x97, 0xcf, 0x09, 0x4f, 0xd7, 0xea, 0x35, 0x2e, 0x5c, 0x15, 0xf4, 0x72, 0x29, 0x76, 0xbd,
	0x22, 0xf6, 0x83, 0xfa, 0x6e, 0x6d, 0xf4, 0x5b, 0x0d, 0x7a, 0x87, 0x28, 0xd5, 0x01, 0x0a, 0xc9,
	0x33, 0x4a, 0xee, 0x42, 0x27, 0x77, 0xa9, 0x1b, 0x07, 0xbd, 0x9d, 0xc1, 0x69, 0x49, 0xc2, 0xd2,
	0x42, 0x17, 0x97, 0xc6, 0x31, 0x4a, 0x9b, 0x6e, 0x37, 0x74, 0x88, 0xdc, 0x81, 0x7a, 0xc1, 0x82,
	0xc6, 0xc9, 0x76, 0xac, 0x5c, 0x33, 0x7e, 0xce, 0xac, 0x92, 0xf5, 0x82, 0x0d, 0x3f, 0x83, 0xb6,
	0x83, 0xff, 0x2b, 0xf2, 0x9f, 0x1b, 0xd0, 0x3b, 0x40, 0x31, 0x63, 0x52, 0x1a, 0x19, 0x03, 0x68,
	0xcf, 0x51, 0xe8, 0xb5, 0x3b, 0xef, 0xa1, 0xee, 0x6b, 0x81, 0x73, 0x66, 0xb6, 0xea, 0xb6, 0xaf,
	0x3d, 0x26, 0x1f, 0x42, 0x4f, 0x87, 0xc7, 0x54, 0xa4, 0xd8, 0xcc, 0x36, 0x63, 0x4d, 0x7f, 0x24,
	0x9a, 0x3a, 0x64, 0x33, 0x24, 0xf7, 0xa1, 0x55, 0x48, 0x14, 0x32, 0x68, 0x9a, 0x6c, 0xae, 0x97,
	0x6a, 0x2c, 0xaf, 0x1e, 0x3f, 0xd7, 0x06, 0x36, 0x21, 0x6b, 0x3c, 0xfc, 0xa5, 0x06, 0xfd, 0xa5,
	0x85, 0xde, 0x27, 0xfb, 0xd0, 0x12, 0x3c, 0x2d, 0x7b, 0x77, 0xeb, 0x3c, 0x47, 0x27, 0x8f, 0x8c,
	0x43, 0x6d, 0xef, 0xfc, 0x9a, 0xb3, 0xe6, 0x0b, 0xa3, 0x13, 0x2f, 0xb7, 0x59, 0x0f, 0x77, 0x01,
	0x96, 0x86, 0x17, 0x49, 0xd8, 0xa8, 0x48, 0x38, 0xfc, 0x0e, 0x60, 0x19, 0xfa, 0x39, 0x27, 0x77,
	0xab, 0x27, 0x7b, 0x3b, 0xa3, 0x8b, 0x43, 0xae, 0x16, 0xe8, 0xc7, 0x1a, 0xc0, 0x5e, 0x1c, 0xf3,
	0x22, 0x53, 0x87, 0x74, 0xa2, 0xab, 0x10, 0x53, 0x85, 0x13, 0x2e, 0xfc, 0x1d, 0x25, 0x26, 0xb7,
	0x2b, 0xfd, 0x32, 0x2c, 0x3f, 0x99, 0xf2, 0xec, 0xbb, 0x68, 0x97, 0xdf, 0x6b, 0x00, 0x5f, 0xf3,
	0x09, 0xcb, 0x9e, 0x29, 0xaa, 0x90, 0xbc, 0x07, 0x1d, 0x96, 0xe4, 0x51, 0x46, 0x67, 0x7e, 0x5c,
	0xb5, 0x59, 0x92, 0x7f, 0x43, 0x67, 0x66, 0x32, 0x09, 0xa4, 0xe9, 0xcc, 0xfb, 0x30, 0x80, 0x5c,
	0x83, 0x6e, 0x9c, 0x32, 0xcc, 0x54, 0xc4, 0x12, 0x37, 0xb3, 0x3a, 0x96, 0x78, 0x92, 0xe8, 0x23,
	0x32, 0xe6, 0x39, 0xba, 0xc9, 0x65, 0x81, 0xed, 0xbb, 0x84, 0x09, 0x8c, 0x95, 0x9b, 0xdf, 0x25,
	0x36, 0x27, 0x74, 0x20, 0x6e, 0xfc, 0x5a, 0xa0, 0xd9, 0x8c, 0x67, 0x31, 0x06, 0x2b, 0x96, 0x35,
	0x60, 0xf4, 0x57, 0x0d, 0xfa, 0x7b, 0x85, 0x9a, 0x1e, 0xf2, 0xd7, 0xe8, 0xc2, 0xaf, 0xba, 0xae,
	0x9d, 0x72, 0x1d, 0x40, 0x5b, 0x16, 0x47, 0xaf, 0xf4, 0x96, 0xcd, 0xc0, 0xc3, 0x65, 0x98, 0x8d,
	0x53, 0x61, 0xe6, 0x82, 0xcf, 0x59, 0x82, 0xc2, 0xc5, 0x5f, 0xe2, 0xa5, 0x16, 0xad, 0xaa, 0x16,
	0x65, 0xf0, 0x9d, 0x0b, 0x83, 0x27, 0x1f, 0x00, 0xa4, 0x5a, 0xf6, 0x68, 0xca, 0x32, 0xe5, 0xb2,
	0xed, 0x1a, 0xe6, 0x31, 0xcb, 0xd4, 0xe8, 0x25, 0xac, 0x9a, 0xb4, 0x9e, 0xa2, 0xa2, 0x09, 0x55,
	0x54, 0x77, 0x78, 0xa5, 0x28, 0x66, 0xad, 0xb5, 0x67, 0x52, 0x16, 0x98, 0x44, 0xd4, 0xe7, 0xd4,
	0xb1, 0xc4, 0x9e, 0x49, 0xd7, 0xbd, 0x8a, 0x2e, 0x2d, 0x0f, 0x47, 0xbf, 0xd6, 0xe1, 0xd2, 0x63,
	0x26, 0x15, 0x17, 0x0b, 0xdb, 0x2f, 0xd5, 0x41, 0x50, 0x3b, 0x35, 0x08, 0x08, 0x34, 0xf5, 0xa7,
	0xeb, 0xdc, 0x9b, 0xf5, 0xc5, 0xc3, 0x81, 0x40, 0x33, 0xa7, 0x6a, 0xea, 0x64, 0x33, 0x6b, 0x2d,
	0xc3, 0x9b, 0x02, 0xc5, 0xc2, 0x4b, 0x66, 0x80, 0xb6, 0x4c, 0x50, 0xc6, 0x4e, 0x1b, 0xb3, 0xd6,
	0xd3, 0x73, 0x86, 0x6a, 0xca, 0x13, 0x27, 0x8b, 0x43, 0xe6, 0xda, 0x29, 0xcd, 0x26, 0x18, 0x99,
	0xd7, 0xd4, 0x8a, 0x0c, 0x96, 0x3a, 0xd4, 0x6f, 0xea, 0x4d, 0xe8, 0x73, 0xc1, 0x26, 0x4c, 0xbf,
	0x18, 0xb6, 0xdd, 0xbb, 0xc6, 0x66, 0xd5, 0xb3, 0x2f, 0xcc, 0x63, 0x7a, 0x13, 0xfa, 0xce, 0x8f,
	0xc0, 0x37, 0x05, 0x4a, 0x15, 0x80, 0x35, 0xb3, 0x6c, 0x68, 0xc9, 0x11, 0x85, 0xb6, 0x53, 0x89,
	0x8c, 0xa1, 0x3d, 0xb5, 0x4b, 0x37, 0xa5, 0xae, 0xf8, 0x8f, 0xb1, 0xaa, 0x63, 0xe8, 0x8d, 0xc8,
	0x2d, 0x58, 0xcb, 0xf0, 0xad, 0x8a, 0x72, 0xaa, 0x83, 0xd5, 0x75, 0x74, 0xfa, 0xad, 0x6a, 0xfa,
	0x80, 0x4e, 0xd0, 0x14, 0x77, 0xf4, 0x77, 0x1d, 0xe0, 0x5b, 0x96, 0xc4, 0xfb, 0x3c, 0x3b, 0x66,
	0x13, 0x9d, 0xb8, 0x29, 0x9f, 0x70, 0x55, 0x76, 0x48, 0xd7, 0xe7, 0xd5, 0xf7, 0xaf, 0x65, 0x54,
	0x08, 0xe6, 0xcb, 0xec, 0x31, 0xd9, 0x82, 0x55, 0x5a, 0xa8, 0x69, 0x84, 0x59, 0x92, 0x73, 0xdd,
	0x4a, 0xb6, 0xd8, 0x57, 0x35, 0xc9, 0x05, 0xfb, 0xc1, 0xfc, 0x1e, 0x2a, 0x77, 0xc9, 0x03, 0x08,
	0x04, 0xca, 0x9c, 0x67, 0xd2, 0xaa, 0x28, 0x23, 0x59, 0xe4, 0xfa, 0xcd, 0xc2, 0xc4, 0x4c, 0xf2,
	0x6e, 0xf8, 0xaf, 0xfb, 0xe4, 0x16, 0xf4, 0x4d, 0x2e, 0xcb, 0xbb, 0x6c, 0x29, 0x4f, 0xb1, 0xe4,
	0x1e, 0x5c, 0x16, 0x38, 0xe7, 0xf1, 0xc9, 0xab, 0x5d, 0xbd, 0xce, 0xdb, 0x22, 0x77, 0x61, 0x5d,
	0x37, 0x16, 0xcb, 0x8e, 0xf9, 0xd2, 0xde, 0xb6, 0xc4, 0xd9, 0x0d, 0x72, 0x1b, 0x06, 0xe6, 0x0b,
	0xad, 0xc6, 0xde, 0x36, 0xb1, 0x9f, 0xe1, 0x47, 0x7f, 0xd4, 0x61, 0x5d, 0x2b, 0x6c, 0xf4, 0x0e,
	0x5d, 0x66, 0x64, 0x04, 0x97, 0xec, 0x8b, 0xec, 0x8a, 0x63, 0xe5, 0x3e, 0xc1, 0x91, 0xeb, 0x00,
	0x36, 0x2f, 0xd3, 0x6c, 0x56, 0xf6, 0x0a, 0xa3, 0xf7, 0xfd, 0xaf, 0x51, 0x96, 0x19, 0xd5, 0x5b,
	0x61, 0x85, 0x21, 0x37, 0x60, 0x55, 0xe0, 0xb1, 0x40, 0x39, 0x75, 0x97, 0xd8, 0x8f, 0xe1, 0x24,
	0xa9, 0x4b, 0xcb, 0x12, 0x67, 0xe0, 0x66, 0xa1, 0xc7, 0xcb, 0xb1, 0xb4, 0x52, 0x1d, 0x4b, 0x03,
	0x68, 0x14, 0xcc, 0x7f, 0x1a, 0x7a, 0x49, 0x76, 0xa0, 0xa9, 0x05, 0x32, 0x02, 0x57, 0x5e, 0xe2,
	0x33, 0x69, 0x8f, 0x9f, 0x64, 0xc7, 0x3c, 0x34, 0xb6, 0xc3, 0x7b, 0xd0, 0xd4, 0xe8, 0xdc, 0xb1,
	0x72, 0x05, 0x5a, 0x38, 0xa3, 0x2c, 0xf5, 0x83, 0xde, 0x80, 0x2f, 0x9e, 0xbf, 0x7c, 0x36, 0x61,
	0x6a, 0x5a, 0x1c, 0x69, 0xff, 0xdb, 0x5f, 0x71, 0x3e, 0x49, 0x71, 0x3f, 0xe5, 0x45, 0x72, 0x90,
	0x52, 0x75, 0xcc, 0xc5, 0x6c, 0x7b, 0x8a, 0x34, 0x55, 0xd3, 0x98, 0x0a, 0xdc, 0x3a, 0xc6, 0x04,
	0x05, 0x55, 0x98, 0x6c, 0x59, 0x4d, 0xb7, 0x24, 0x8a, 0x39, 0x8b, 0x51, 0x6e, 0x9f, 0xfa, 0x9b,
	0x71, 0xb4, 0x62, 0x88, 0x4f, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x52, 0x7a, 0x18, 0x80,
	0x0c, 0x00, 0x00,
}
