// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/common/v1/common.proto

// Package com defines messages shared between IC and DAM server.

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Descriptor struct {
	Label                string   `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Regexp               string   `protobuf:"bytes,3,opt,name=regexp,proto3" json:"regexp,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	IsList               bool     `protobuf:"varint,5,opt,name=is_list,json=isList,proto3" json:"is_list,omitempty"`
	EnumValues           []string `protobuf:"bytes,6,rep,name=enum_values,json=enumValues,proto3" json:"enum_values,omitempty"`
	Min                  string   `protobuf:"bytes,7,opt,name=min,proto3" json:"min,omitempty"`
	Max                  string   `protobuf:"bytes,8,opt,name=max,proto3" json:"max,omitempty"`
	DefaultValue         string   `protobuf:"bytes,9,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Descriptor) Reset()         { *m = Descriptor{} }
func (m *Descriptor) String() string { return proto.CompactTextString(m) }
func (*Descriptor) ProtoMessage()    {}
func (*Descriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_988ca6f500b2cf3b, []int{0}
}

func (m *Descriptor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Descriptor.Unmarshal(m, b)
}
func (m *Descriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Descriptor.Marshal(b, m, deterministic)
}
func (m *Descriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Descriptor.Merge(m, src)
}
func (m *Descriptor) XXX_Size() int {
	return xxx_messageInfo_Descriptor.Size(m)
}
func (m *Descriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_Descriptor.DiscardUnknown(m)
}

var xxx_messageInfo_Descriptor proto.InternalMessageInfo

func (m *Descriptor) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Descriptor) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Descriptor) GetRegexp() string {
	if m != nil {
		return m.Regexp
	}
	return ""
}

func (m *Descriptor) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Descriptor) GetIsList() bool {
	if m != nil {
		return m.IsList
	}
	return false
}

func (m *Descriptor) GetEnumValues() []string {
	if m != nil {
		return m.EnumValues
	}
	return nil
}

func (m *Descriptor) GetMin() string {
	if m != nil {
		return m.Min
	}
	return ""
}

func (m *Descriptor) GetMax() string {
	if m != nil {
		return m.Max
	}
	return ""
}

func (m *Descriptor) GetDefaultValue() string {
	if m != nil {
		return m.DefaultValue
	}
	return ""
}

type Condition struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	By                   string   `protobuf:"bytes,4,opt,name=by,proto3" json:"by,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Condition) Reset()         { *m = Condition{} }
func (m *Condition) String() string { return proto.CompactTextString(m) }
func (*Condition) ProtoMessage()    {}
func (*Condition) Descriptor() ([]byte, []int) {
	return fileDescriptor_988ca6f500b2cf3b, []int{1}
}

func (m *Condition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Condition.Unmarshal(m, b)
}
func (m *Condition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Condition.Marshal(b, m, deterministic)
}
func (m *Condition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Condition.Merge(m, src)
}
func (m *Condition) XXX_Size() int {
	return xxx_messageInfo_Condition.Size(m)
}
func (m *Condition) XXX_DiscardUnknown() {
	xxx_messageInfo_Condition.DiscardUnknown(m)
}

var xxx_messageInfo_Condition proto.InternalMessageInfo

func (m *Condition) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Condition) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Condition) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Condition) GetBy() string {
	if m != nil {
		return m.By
	}
	return ""
}

type ConditionSet struct {
	AllOf                []*Condition `protobuf:"bytes,1,rep,name=all_of,json=allOf,proto3" json:"all_of,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ConditionSet) Reset()         { *m = ConditionSet{} }
func (m *ConditionSet) String() string { return proto.CompactTextString(m) }
func (*ConditionSet) ProtoMessage()    {}
func (*ConditionSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_988ca6f500b2cf3b, []int{2}
}

func (m *ConditionSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConditionSet.Unmarshal(m, b)
}
func (m *ConditionSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConditionSet.Marshal(b, m, deterministic)
}
func (m *ConditionSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConditionSet.Merge(m, src)
}
func (m *ConditionSet) XXX_Size() int {
	return xxx_messageInfo_ConditionSet.Size(m)
}
func (m *ConditionSet) XXX_DiscardUnknown() {
	xxx_messageInfo_ConditionSet.DiscardUnknown(m)
}

var xxx_messageInfo_ConditionSet proto.InternalMessageInfo

func (m *ConditionSet) GetAllOf() []*Condition {
	if m != nil {
		return m.AllOf
	}
	return nil
}

type Assertion struct {
	Type             string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Source           string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Value            string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	AssertedDuration string `protobuf:"bytes,4,opt,name=asserted_duration,json=assertedDuration,proto3" json:"asserted_duration,omitempty"`
	ExpiresDuration  string `protobuf:"bytes,5,opt,name=expires_duration,json=expiresDuration,proto3" json:"expires_duration,omitempty"`
	// Disjunction of Conjunctions (OR of ANDs).
	// If at least one of these ConditionSets evaluates to true, then the
	// conditions on this assertion have been met.
	AnyOfConditions      []*ConditionSet `protobuf:"bytes,6,rep,name=any_of_conditions,json=anyOfConditions,proto3" json:"any_of_conditions,omitempty"`
	By                   string          `protobuf:"bytes,7,opt,name=by,proto3" json:"by,omitempty"`
	Asserted             int64           `protobuf:"varint,8,opt,name=asserted,proto3" json:"asserted,omitempty"`
	Exp                  int64           `protobuf:"varint,9,opt,name=exp,proto3" json:"exp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Assertion) Reset()         { *m = Assertion{} }
func (m *Assertion) String() string { return proto.CompactTextString(m) }
func (*Assertion) ProtoMessage()    {}
func (*Assertion) Descriptor() ([]byte, []int) {
	return fileDescriptor_988ca6f500b2cf3b, []int{3}
}

func (m *Assertion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Assertion.Unmarshal(m, b)
}
func (m *Assertion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Assertion.Marshal(b, m, deterministic)
}
func (m *Assertion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Assertion.Merge(m, src)
}
func (m *Assertion) XXX_Size() int {
	return xxx_messageInfo_Assertion.Size(m)
}
func (m *Assertion) XXX_DiscardUnknown() {
	xxx_messageInfo_Assertion.DiscardUnknown(m)
}

var xxx_messageInfo_Assertion proto.InternalMessageInfo

func (m *Assertion) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Assertion) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Assertion) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Assertion) GetAssertedDuration() string {
	if m != nil {
		return m.AssertedDuration
	}
	return ""
}

func (m *Assertion) GetExpiresDuration() string {
	if m != nil {
		return m.ExpiresDuration
	}
	return ""
}

func (m *Assertion) GetAnyOfConditions() []*ConditionSet {
	if m != nil {
		return m.AnyOfConditions
	}
	return nil
}

func (m *Assertion) GetBy() string {
	if m != nil {
		return m.By
	}
	return ""
}

func (m *Assertion) GetAsserted() int64 {
	if m != nil {
		return m.Asserted
	}
	return 0
}

func (m *Assertion) GetExp() int64 {
	if m != nil {
		return m.Exp
	}
	return 0
}

type Passport struct {
	StandardClaims         map[string]string `protobuf:"bytes,1,rep,name=standard_claims,json=standardClaims,proto3" json:"standard_claims,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Ga4GhAssertions        []*Assertion      `protobuf:"bytes,2,rep,name=ga4gh_assertions,json=ga4ghAssertions,proto3" json:"ga4gh_assertions,omitempty"`
	InternalEncryptedVisas [][]byte          `protobuf:"bytes,11,rep,name=internal_encrypted_visas,json=internalEncryptedVisas,proto3" json:"internal_encrypted_visas,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}          `json:"-"`
	XXX_unrecognized       []byte            `json:"-"`
	XXX_sizecache          int32             `json:"-"`
}

func (m *Passport) Reset()         { *m = Passport{} }
func (m *Passport) String() string { return proto.CompactTextString(m) }
func (*Passport) ProtoMessage()    {}
func (*Passport) Descriptor() ([]byte, []int) {
	return fileDescriptor_988ca6f500b2cf3b, []int{4}
}

func (m *Passport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Passport.Unmarshal(m, b)
}
func (m *Passport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Passport.Marshal(b, m, deterministic)
}
func (m *Passport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Passport.Merge(m, src)
}
func (m *Passport) XXX_Size() int {
	return xxx_messageInfo_Passport.Size(m)
}
func (m *Passport) XXX_DiscardUnknown() {
	xxx_messageInfo_Passport.DiscardUnknown(m)
}

var xxx_messageInfo_Passport proto.InternalMessageInfo

func (m *Passport) GetStandardClaims() map[string]string {
	if m != nil {
		return m.StandardClaims
	}
	return nil
}

func (m *Passport) GetGa4GhAssertions() []*Assertion {
	if m != nil {
		return m.Ga4GhAssertions
	}
	return nil
}

func (m *Passport) GetInternalEncryptedVisas() [][]byte {
	if m != nil {
		return m.InternalEncryptedVisas
	}
	return nil
}

type TestPersona struct {
	Passport             *Passport         `protobuf:"bytes,1,opt,name=passport,proto3" json:"passport,omitempty"`
	Access               []string          `protobuf:"bytes,2,rep,name=access,proto3" json:"access,omitempty"`
	Ui                   map[string]string `protobuf:"bytes,3,rep,name=ui,proto3" json:"ui,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TestPersona) Reset()         { *m = TestPersona{} }
func (m *TestPersona) String() string { return proto.CompactTextString(m) }
func (*TestPersona) ProtoMessage()    {}
func (*TestPersona) Descriptor() ([]byte, []int) {
	return fileDescriptor_988ca6f500b2cf3b, []int{5}
}

func (m *TestPersona) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestPersona.Unmarshal(m, b)
}
func (m *TestPersona) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestPersona.Marshal(b, m, deterministic)
}
func (m *TestPersona) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestPersona.Merge(m, src)
}
func (m *TestPersona) XXX_Size() int {
	return xxx_messageInfo_TestPersona.Size(m)
}
func (m *TestPersona) XXX_DiscardUnknown() {
	xxx_messageInfo_TestPersona.DiscardUnknown(m)
}

var xxx_messageInfo_TestPersona proto.InternalMessageInfo

func (m *TestPersona) GetPassport() *Passport {
	if m != nil {
		return m.Passport
	}
	return nil
}

func (m *TestPersona) GetAccess() []string {
	if m != nil {
		return m.Access
	}
	return nil
}

func (m *TestPersona) GetUi() map[string]string {
	if m != nil {
		return m.Ui
	}
	return nil
}

type Permissions struct {
	Version              string                                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Revision             int64                                  `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	CommitTime           float64                                `protobuf:"fixed64,3,opt,name=commit_time,json=commitTime,proto3" json:"commit_time,omitempty"`
	Users                map[string]*Permissions_PermissionUser `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *Permissions) Reset()         { *m = Permissions{} }
func (m *Permissions) String() string { return proto.CompactTextString(m) }
func (*Permissions) ProtoMessage()    {}
func (*Permissions) Descriptor() ([]byte, []int) {
	return fileDescriptor_988ca6f500b2cf3b, []int{6}
}

func (m *Permissions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Permissions.Unmarshal(m, b)
}
func (m *Permissions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Permissions.Marshal(b, m, deterministic)
}
func (m *Permissions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Permissions.Merge(m, src)
}
func (m *Permissions) XXX_Size() int {
	return xxx_messageInfo_Permissions.Size(m)
}
func (m *Permissions) XXX_DiscardUnknown() {
	xxx_messageInfo_Permissions.DiscardUnknown(m)
}

var xxx_messageInfo_Permissions proto.InternalMessageInfo

func (m *Permissions) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Permissions) GetRevision() int64 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *Permissions) GetCommitTime() float64 {
	if m != nil {
		return m.CommitTime
	}
	return 0
}

func (m *Permissions) GetUsers() map[string]*Permissions_PermissionUser {
	if m != nil {
		return m.Users
	}
	return nil
}

type Permissions_PermissionUser struct {
	Roles                map[string]int64 `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Permissions_PermissionUser) Reset()         { *m = Permissions_PermissionUser{} }
func (m *Permissions_PermissionUser) String() string { return proto.CompactTextString(m) }
func (*Permissions_PermissionUser) ProtoMessage()    {}
func (*Permissions_PermissionUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_988ca6f500b2cf3b, []int{6, 0}
}

func (m *Permissions_PermissionUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Permissions_PermissionUser.Unmarshal(m, b)
}
func (m *Permissions_PermissionUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Permissions_PermissionUser.Marshal(b, m, deterministic)
}
func (m *Permissions_PermissionUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Permissions_PermissionUser.Merge(m, src)
}
func (m *Permissions_PermissionUser) XXX_Size() int {
	return xxx_messageInfo_Permissions_PermissionUser.Size(m)
}
func (m *Permissions_PermissionUser) XXX_DiscardUnknown() {
	xxx_messageInfo_Permissions_PermissionUser.DiscardUnknown(m)
}

var xxx_messageInfo_Permissions_PermissionUser proto.InternalMessageInfo

func (m *Permissions_PermissionUser) GetRoles() map[string]int64 {
	if m != nil {
		return m.Roles
	}
	return nil
}

// LoginState records states for login and login callback.
type LoginState struct {
	IdpName  string `protobuf:"bytes,1,opt,name=idp_name,json=idpName,proto3" json:"idp_name,omitempty"`
	Realm    string `protobuf:"bytes,2,opt,name=realm,proto3" json:"realm,omitempty"`
	ClientId string `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // Deprecated: Do not use.
	// TODO should also deprecate scope after hydra integration
	// complete.
	Scope                string   `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	Redirect             string   `protobuf:"bytes,5,opt,name=redirect,proto3" json:"redirect,omitempty"` // Deprecated: Do not use.
	State                string   `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`       // Deprecated: Do not use.
	Nonce                string   `protobuf:"bytes,6,opt,name=nonce,proto3" json:"nonce,omitempty"`       // Deprecated: Do not use.
	Challenge            string   `protobuf:"bytes,8,opt,name=challenge,proto3" json:"challenge,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginState) Reset()         { *m = LoginState{} }
func (m *LoginState) String() string { return proto.CompactTextString(m) }
func (*LoginState) ProtoMessage()    {}
func (*LoginState) Descriptor() ([]byte, []int) {
	return fileDescriptor_988ca6f500b2cf3b, []int{7}
}

func (m *LoginState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginState.Unmarshal(m, b)
}
func (m *LoginState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginState.Marshal(b, m, deterministic)
}
func (m *LoginState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginState.Merge(m, src)
}
func (m *LoginState) XXX_Size() int {
	return xxx_messageInfo_LoginState.Size(m)
}
func (m *LoginState) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginState.DiscardUnknown(m)
}

var xxx_messageInfo_LoginState proto.InternalMessageInfo

func (m *LoginState) GetIdpName() string {
	if m != nil {
		return m.IdpName
	}
	return ""
}

func (m *LoginState) GetRealm() string {
	if m != nil {
		return m.Realm
	}
	return ""
}

// Deprecated: Do not use.
func (m *LoginState) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *LoginState) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

// Deprecated: Do not use.
func (m *LoginState) GetRedirect() string {
	if m != nil {
		return m.Redirect
	}
	return ""
}

// Deprecated: Do not use.
func (m *LoginState) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

// Deprecated: Do not use.
func (m *LoginState) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *LoginState) GetChallenge() string {
	if m != nil {
		return m.Challenge
	}
	return ""
}

// AuthTokenState records states for create auth token.
type AuthTokenState struct {
	Redirect             string   `protobuf:"bytes,1,opt,name=redirect,proto3" json:"redirect,omitempty"` // Deprecated: Do not use.
	Subject              string   `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Scope                string   `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	Provider             string   `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	Realm                string   `protobuf:"bytes,5,opt,name=realm,proto3" json:"realm,omitempty"`
	State                string   `protobuf:"bytes,8,opt,name=state,proto3" json:"state,omitempty"` // Deprecated: Do not use.
	Nonce                string   `protobuf:"bytes,6,opt,name=nonce,proto3" json:"nonce,omitempty"` // Deprecated: Do not use.
	LoginHint            string   `protobuf:"bytes,7,opt,name=login_hint,json=loginHint,proto3" json:"login_hint,omitempty"`
	ConsentChallenge     string   `protobuf:"bytes,9,opt,name=consent_challenge,json=consentChallenge,proto3" json:"consent_challenge,omitempty"`
	Audience             []string `protobuf:"bytes,10,rep,name=audience,proto3" json:"audience,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthTokenState) Reset()         { *m = AuthTokenState{} }
func (m *AuthTokenState) String() string { return proto.CompactTextString(m) }
func (*AuthTokenState) ProtoMessage()    {}
func (*AuthTokenState) Descriptor() ([]byte, []int) {
	return fileDescriptor_988ca6f500b2cf3b, []int{8}
}

func (m *AuthTokenState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthTokenState.Unmarshal(m, b)
}
func (m *AuthTokenState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthTokenState.Marshal(b, m, deterministic)
}
func (m *AuthTokenState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthTokenState.Merge(m, src)
}
func (m *AuthTokenState) XXX_Size() int {
	return xxx_messageInfo_AuthTokenState.Size(m)
}
func (m *AuthTokenState) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthTokenState.DiscardUnknown(m)
}

var xxx_messageInfo_AuthTokenState proto.InternalMessageInfo

// Deprecated: Do not use.
func (m *AuthTokenState) GetRedirect() string {
	if m != nil {
		return m.Redirect
	}
	return ""
}

func (m *AuthTokenState) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *AuthTokenState) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *AuthTokenState) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *AuthTokenState) GetRealm() string {
	if m != nil {
		return m.Realm
	}
	return ""
}

// Deprecated: Do not use.
func (m *AuthTokenState) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

// Deprecated: Do not use.
func (m *AuthTokenState) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *AuthTokenState) GetLoginHint() string {
	if m != nil {
		return m.LoginHint
	}
	return ""
}

func (m *AuthTokenState) GetConsentChallenge() string {
	if m != nil {
		return m.ConsentChallenge
	}
	return ""
}

func (m *AuthTokenState) GetAudience() []string {
	if m != nil {
		return m.Audience
	}
	return nil
}

type TokenMetadata struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IssuedAt             string   `protobuf:"bytes,2,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	Expires              string   `protobuf:"bytes,3,opt,name=expires,proto3" json:"expires,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenMetadata) Reset()         { *m = TokenMetadata{} }
func (m *TokenMetadata) String() string { return proto.CompactTextString(m) }
func (*TokenMetadata) ProtoMessage()    {}
func (*TokenMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_988ca6f500b2cf3b, []int{9}
}

func (m *TokenMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenMetadata.Unmarshal(m, b)
}
func (m *TokenMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenMetadata.Marshal(b, m, deterministic)
}
func (m *TokenMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenMetadata.Merge(m, src)
}
func (m *TokenMetadata) XXX_Size() int {
	return xxx_messageInfo_TokenMetadata.Size(m)
}
func (m *TokenMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_TokenMetadata proto.InternalMessageInfo

func (m *TokenMetadata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TokenMetadata) GetIssuedAt() string {
	if m != nil {
		return m.IssuedAt
	}
	return ""
}

func (m *TokenMetadata) GetExpires() string {
	if m != nil {
		return m.Expires
	}
	return ""
}

type HistoryEntry struct {
	Revision             int64    `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	CommitTime           float64  `protobuf:"fixed64,3,opt,name=commit_time,json=commitTime,proto3" json:"commit_time,omitempty"`
	Path                 string   `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Query                string   `protobuf:"bytes,5,opt,name=query,proto3" json:"query,omitempty"`
	Desc                 string   `protobuf:"bytes,6,opt,name=desc,proto3" json:"desc,omitempty"`
	Method               string   `protobuf:"bytes,7,opt,name=method,proto3" json:"method,omitempty"`
	ChangeType           string   `protobuf:"bytes,8,opt,name=change_type,json=changeType,proto3" json:"change_type,omitempty"`
	OriginalValue        string   `protobuf:"bytes,9,opt,name=original_value,json=originalValue,proto3" json:"original_value,omitempty"`
	ChangeRequest        string   `protobuf:"bytes,10,opt,name=change_request,json=changeRequest,proto3" json:"change_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HistoryEntry) Reset()         { *m = HistoryEntry{} }
func (m *HistoryEntry) String() string { return proto.CompactTextString(m) }
func (*HistoryEntry) ProtoMessage()    {}
func (*HistoryEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_988ca6f500b2cf3b, []int{10}
}

func (m *HistoryEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistoryEntry.Unmarshal(m, b)
}
func (m *HistoryEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistoryEntry.Marshal(b, m, deterministic)
}
func (m *HistoryEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoryEntry.Merge(m, src)
}
func (m *HistoryEntry) XXX_Size() int {
	return xxx_messageInfo_HistoryEntry.Size(m)
}
func (m *HistoryEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoryEntry.DiscardUnknown(m)
}

var xxx_messageInfo_HistoryEntry proto.InternalMessageInfo

func (m *HistoryEntry) GetRevision() int64 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *HistoryEntry) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *HistoryEntry) GetCommitTime() float64 {
	if m != nil {
		return m.CommitTime
	}
	return 0
}

func (m *HistoryEntry) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *HistoryEntry) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *HistoryEntry) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *HistoryEntry) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *HistoryEntry) GetChangeType() string {
	if m != nil {
		return m.ChangeType
	}
	return ""
}

func (m *HistoryEntry) GetOriginalValue() string {
	if m != nil {
		return m.OriginalValue
	}
	return ""
}

func (m *HistoryEntry) GetChangeRequest() string {
	if m != nil {
		return m.ChangeRequest
	}
	return ""
}

type History struct {
	History              []*HistoryEntry `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	NextPageToken        string          `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *History) Reset()         { *m = History{} }
func (m *History) String() string { return proto.CompactTextString(m) }
func (*History) ProtoMessage()    {}
func (*History) Descriptor() ([]byte, []int) {
	return fileDescriptor_988ca6f500b2cf3b, []int{11}
}

func (m *History) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_History.Unmarshal(m, b)
}
func (m *History) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_History.Marshal(b, m, deterministic)
}
func (m *History) XXX_Merge(src proto.Message) {
	xxx_messageInfo_History.Merge(m, src)
}
func (m *History) XXX_Size() int {
	return xxx_messageInfo_History.Size(m)
}
func (m *History) XXX_DiscardUnknown() {
	xxx_messageInfo_History.DiscardUnknown(m)
}

var xxx_messageInfo_History proto.InternalMessageInfo

func (m *History) GetHistory() []*HistoryEntry {
	if m != nil {
		return m.History
	}
	return nil
}

func (m *History) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type OidcConfig struct {
	Issuer                 string   `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	JwksUri                string   `protobuf:"bytes,2,opt,name=jwks_uri,proto3" json:"jwks_uri,omitempty"`
	AuthEndpoint           string   `protobuf:"bytes,3,opt,name=auth_endpoint,json=authorization_endpoint,proto3" json:"auth_endpoint,omitempty"`
	ResponseTypesSupported []string `protobuf:"bytes,4,rep,name=response_types_supported,proto3" json:"response_types_supported,omitempty"`
	TokenEndpoint          string   `protobuf:"bytes,5,opt,name=token_endpoint,proto3" json:"token_endpoint,omitempty"`
	RevocationEndpoint     string   `protobuf:"bytes,8,opt,name=revocation_endpoint,proto3" json:"revocation_endpoint,omitempty"`
	UserinfoEndpoint       string   `protobuf:"bytes,6,opt,name=userinfo_endpoint,proto3" json:"userinfo_endpoint,omitempty"`
	ScopesSupported        []string `protobuf:"bytes,7,rep,name=scopes_supported,proto3" json:"scopes_supported,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *OidcConfig) Reset()         { *m = OidcConfig{} }
func (m *OidcConfig) String() string { return proto.CompactTextString(m) }
func (*OidcConfig) ProtoMessage()    {}
func (*OidcConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_988ca6f500b2cf3b, []int{12}
}

func (m *OidcConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OidcConfig.Unmarshal(m, b)
}
func (m *OidcConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OidcConfig.Marshal(b, m, deterministic)
}
func (m *OidcConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OidcConfig.Merge(m, src)
}
func (m *OidcConfig) XXX_Size() int {
	return xxx_messageInfo_OidcConfig.Size(m)
}
func (m *OidcConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_OidcConfig.DiscardUnknown(m)
}

var xxx_messageInfo_OidcConfig proto.InternalMessageInfo

func (m *OidcConfig) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *OidcConfig) GetJwksUri() string {
	if m != nil {
		return m.JwksUri
	}
	return ""
}

func (m *OidcConfig) GetAuthEndpoint() string {
	if m != nil {
		return m.AuthEndpoint
	}
	return ""
}

func (m *OidcConfig) GetResponseTypesSupported() []string {
	if m != nil {
		return m.ResponseTypesSupported
	}
	return nil
}

func (m *OidcConfig) GetTokenEndpoint() string {
	if m != nil {
		return m.TokenEndpoint
	}
	return ""
}

func (m *OidcConfig) GetRevocationEndpoint() string {
	if m != nil {
		return m.RevocationEndpoint
	}
	return ""
}

func (m *OidcConfig) GetUserinfoEndpoint() string {
	if m != nil {
		return m.UserinfoEndpoint
	}
	return ""
}

func (m *OidcConfig) GetScopesSupported() []string {
	if m != nil {
		return m.ScopesSupported
	}
	return nil
}

type OidcTokenResponse struct {
	AccessToken          string                  `protobuf:"bytes,1,opt,name=access_token,proto3" json:"access_token,omitempty"`
	TokenType            string                  `protobuf:"bytes,2,opt,name=token_type,proto3" json:"token_type,omitempty"`
	ExpiresIn            int32                   `protobuf:"varint,3,opt,name=expires_in,proto3" json:"expires_in,omitempty"`
	RefreshToken         string                  `protobuf:"bytes,4,opt,name=refresh_token,proto3" json:"refresh_token,omitempty"`
	IdToken              string                  `protobuf:"bytes,5,opt,name=id_token,proto3" json:"id_token,omitempty"`
	Scope                string                  `protobuf:"bytes,6,opt,name=scope,proto3" json:"scope,omitempty"`
	Uid                  string                  `protobuf:"bytes,7,opt,name=uid,proto3" json:"uid,omitempty"`
	Info                 *OidcTokenResponse_Info `protobuf:"bytes,8,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *OidcTokenResponse) Reset()         { *m = OidcTokenResponse{} }
func (m *OidcTokenResponse) String() string { return proto.CompactTextString(m) }
func (*OidcTokenResponse) ProtoMessage()    {}
func (*OidcTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_988ca6f500b2cf3b, []int{13}
}

func (m *OidcTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OidcTokenResponse.Unmarshal(m, b)
}
func (m *OidcTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OidcTokenResponse.Marshal(b, m, deterministic)
}
func (m *OidcTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OidcTokenResponse.Merge(m, src)
}
func (m *OidcTokenResponse) XXX_Size() int {
	return xxx_messageInfo_OidcTokenResponse.Size(m)
}
func (m *OidcTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OidcTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OidcTokenResponse proto.InternalMessageInfo

func (m *OidcTokenResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *OidcTokenResponse) GetTokenType() string {
	if m != nil {
		return m.TokenType
	}
	return ""
}

func (m *OidcTokenResponse) GetExpiresIn() int32 {
	if m != nil {
		return m.ExpiresIn
	}
	return 0
}

func (m *OidcTokenResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *OidcTokenResponse) GetIdToken() string {
	if m != nil {
		return m.IdToken
	}
	return ""
}

func (m *OidcTokenResponse) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *OidcTokenResponse) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OidcTokenResponse) GetInfo() *OidcTokenResponse_Info {
	if m != nil {
		return m.Info
	}
	return nil
}

type OidcTokenResponse_Info struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OidcTokenResponse_Info) Reset()         { *m = OidcTokenResponse_Info{} }
func (m *OidcTokenResponse_Info) String() string { return proto.CompactTextString(m) }
func (*OidcTokenResponse_Info) ProtoMessage()    {}
func (*OidcTokenResponse_Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_988ca6f500b2cf3b, []int{13, 0}
}

func (m *OidcTokenResponse_Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OidcTokenResponse_Info.Unmarshal(m, b)
}
func (m *OidcTokenResponse_Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OidcTokenResponse_Info.Marshal(b, m, deterministic)
}
func (m *OidcTokenResponse_Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OidcTokenResponse_Info.Merge(m, src)
}
func (m *OidcTokenResponse_Info) XXX_Size() int {
	return xxx_messageInfo_OidcTokenResponse_Info.Size(m)
}
func (m *OidcTokenResponse_Info) XXX_DiscardUnknown() {
	xxx_messageInfo_OidcTokenResponse_Info.DiscardUnknown(m)
}

var xxx_messageInfo_OidcTokenResponse_Info proto.InternalMessageInfo

func (m *OidcTokenResponse_Info) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OidcTokenResponse_Info) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*Descriptor)(nil), "common.Descriptor")
	proto.RegisterType((*Condition)(nil), "common.Condition")
	proto.RegisterType((*ConditionSet)(nil), "common.ConditionSet")
	proto.RegisterType((*Assertion)(nil), "common.Assertion")
	proto.RegisterType((*Passport)(nil), "common.Passport")
	proto.RegisterMapType((map[string]string)(nil), "common.Passport.StandardClaimsEntry")
	proto.RegisterType((*TestPersona)(nil), "common.TestPersona")
	proto.RegisterMapType((map[string]string)(nil), "common.TestPersona.UiEntry")
	proto.RegisterType((*Permissions)(nil), "common.Permissions")
	proto.RegisterMapType((map[string]*Permissions_PermissionUser)(nil), "common.Permissions.UsersEntry")
	proto.RegisterType((*Permissions_PermissionUser)(nil), "common.Permissions.PermissionUser")
	proto.RegisterMapType((map[string]int64)(nil), "common.Permissions.PermissionUser.RolesEntry")
	proto.RegisterType((*LoginState)(nil), "common.LoginState")
	proto.RegisterType((*AuthTokenState)(nil), "common.AuthTokenState")
	proto.RegisterType((*TokenMetadata)(nil), "common.TokenMetadata")
	proto.RegisterType((*HistoryEntry)(nil), "common.HistoryEntry")
	proto.RegisterType((*History)(nil), "common.History")
	proto.RegisterType((*OidcConfig)(nil), "common.OidcConfig")
	proto.RegisterType((*OidcTokenResponse)(nil), "common.OidcTokenResponse")
	proto.RegisterType((*OidcTokenResponse_Info)(nil), "common.OidcTokenResponse.Info")
}

func init() { proto.RegisterFile("proto/common/v1/common.proto", fileDescriptor_988ca6f500b2cf3b) }

var fileDescriptor_988ca6f500b2cf3b = []byte{
	// 1456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xcb, 0x6e, 0x1b, 0xc7,
	0x12, 0x05, 0x87, 0xe2, 0xab, 0xa8, 0x07, 0xd5, 0x36, 0x74, 0xe7, 0xd2, 0xbe, 0xb6, 0xc0, 0xeb,
	0x18, 0x4a, 0x6c, 0x51, 0x8e, 0xe2, 0x00, 0x82, 0x91, 0x45, 0x64, 0xd9, 0x88, 0x0d, 0xd8, 0xb1,
	0x30, 0x92, 0xbd, 0x30, 0x12, 0x0c, 0x5a, 0x33, 0x45, 0xb2, 0xed, 0xe1, 0xf4, 0xb8, 0xbb, 0x87,
	0x11, 0xf3, 0x09, 0xd9, 0x64, 0x93, 0x4f, 0x48, 0xb6, 0xd9, 0xe6, 0x13, 0xf2, 0x19, 0xd9, 0xe5,
	0x07, 0xf2, 0x03, 0x41, 0x3f, 0x66, 0x38, 0x7a, 0x04, 0x4e, 0x80, 0xec, 0xba, 0x4e, 0x55, 0xf7,
	0x54, 0x9d, 0xd3, 0x5d, 0x45, 0xc2, 0xf5, 0x4c, 0x70, 0xc5, 0x77, 0x22, 0x3e, 0x9d, 0xf2, 0x74,
	0x67, 0xf6, 0xb1, 0x5b, 0x0d, 0x0d, 0x4c, 0x9a, 0xd6, 0x1a, 0xfc, 0x51, 0x03, 0x78, 0x84, 0x32,
	0x12, 0x2c, 0x53, 0x5c, 0x90, 0xab, 0xd0, 0x48, 0xe8, 0x09, 0x26, 0x7e, 0x6d, 0xb3, 0xb6, 0xd5,
	0x09, 0xac, 0x41, 0x36, 0xa1, 0x1b, 0xbb, 0x18, 0xc6, 0x53, 0xdf, 0x33, 0xbe, 0x2a, 0x44, 0x36,
	0xa0, 0x29, 0x70, 0x8c, 0xa7, 0x99, 0x5f, 0x37, 0x4e, 0x67, 0x11, 0x02, 0x4b, 0x6a, 0x9e, 0xa1,
	0xbf, 0x64, 0x50, 0xb3, 0x26, 0xff, 0x81, 0x16, 0x93, 0x61, 0xc2, 0xa4, 0xf2, 0x1b, 0x9b, 0xb5,
	0xad, 0x76, 0xd0, 0x64, 0xf2, 0x19, 0x93, 0x8a, 0xdc, 0x84, 0x2e, 0xa6, 0xf9, 0x34, 0x9c, 0xd1,
	0x24, 0x47, 0xe9, 0x37, 0x37, 0xeb, 0x5b, 0x9d, 0x00, 0x34, 0xf4, 0xca, 0x20, 0xa4, 0x07, 0xf5,
	0x29, 0x4b, 0xfd, 0x96, 0x39, 0x4c, 0x2f, 0x0d, 0x42, 0x4f, 0xfd, 0xb6, 0x43, 0xe8, 0x29, 0xf9,
	0x3f, 0xac, 0xc4, 0x38, 0xa2, 0x79, 0xa2, 0xec, 0x39, 0x7e, 0xc7, 0xf8, 0x96, 0x1d, 0x68, 0x4e,
	0x1a, 0x7c, 0x0d, 0x9d, 0x03, 0x9e, 0xc6, 0xcc, 0xe4, 0x5e, 0xe4, 0x58, 0xab, 0xe4, 0xb8, 0x01,
	0x4d, 0xc9, 0x73, 0x11, 0xa1, 0x2b, 0xd6, 0x59, 0x9a, 0x1f, 0x7b, 0xaa, 0x2d, 0xd3, 0x1a, 0x64,
	0x15, 0xbc, 0x93, 0xb9, 0xab, 0xd1, 0x3b, 0x99, 0x0f, 0xf6, 0x60, 0xb9, 0x3c, 0xfe, 0x08, 0x15,
	0xd9, 0x82, 0x26, 0x4d, 0x92, 0x90, 0x8f, 0xfc, 0xda, 0x66, 0x7d, 0xab, 0xbb, 0xbb, 0x3e, 0x74,
	0x5a, 0x94, 0x51, 0x41, 0x83, 0x26, 0xc9, 0x8b, 0xd1, 0xe0, 0x27, 0x0f, 0x3a, 0xfb, 0x52, 0xa2,
	0xf8, 0x97, 0x32, 0xbb, 0x03, 0xeb, 0xd4, 0x1c, 0x87, 0x71, 0x18, 0xe7, 0x82, 0x1a, 0xfd, 0x6c,
	0xa2, 0xbd, 0xc2, 0xf1, 0xc8, 0xe1, 0xe4, 0x43, 0xe8, 0xe1, 0x69, 0xc6, 0x04, 0xca, 0x45, 0x6c,
	0xc3, 0xc4, 0xae, 0x39, 0xbc, 0x0c, 0xfd, 0x1c, 0xd6, 0x69, 0x3a, 0x0f, 0xf9, 0x28, 0x8c, 0x8a,
	0x12, 0xac, 0x60, 0xdd, 0xdd, 0xab, 0x17, 0x8a, 0x3b, 0x42, 0x15, 0xac, 0xd1, 0x74, 0xfe, 0x62,
	0x54, 0x42, 0xd2, 0x71, 0xd6, 0x2a, 0x38, 0x23, 0x7d, 0x68, 0x17, 0x09, 0x19, 0x39, 0xeb, 0x41,
	0x69, 0x6b, 0x95, 0xf5, 0xd5, 0xea, 0x18, 0x58, 0x2f, 0x07, 0x3f, 0x78, 0xd0, 0x3e, 0xa4, 0x52,
	0x66, 0x5c, 0x28, 0xf2, 0x1c, 0xd6, 0xa4, 0xa2, 0x69, 0x4c, 0x45, 0x1c, 0x46, 0x09, 0x65, 0x53,
	0xe9, 0x78, 0xbe, 0x55, 0xa4, 0x52, 0x84, 0x0e, 0x8f, 0x5c, 0xdc, 0x81, 0x09, 0x7b, 0x9c, 0x2a,
	0x31, 0x0f, 0x56, 0xe5, 0x19, 0x90, 0x7c, 0x06, 0xbd, 0x31, 0xbd, 0x3f, 0x9e, 0x84, 0xb4, 0x10,
	0x42, 0xfa, 0xde, 0x59, 0xdd, 0x4a, 0x89, 0x82, 0x35, 0x13, 0x5a, 0xda, 0x92, 0xec, 0x81, 0xcf,
	0x52, 0x85, 0x22, 0xa5, 0x49, 0x88, 0x69, 0x24, 0xe6, 0x99, 0xe6, 0x7e, 0xc6, 0x24, 0x95, 0x7e,
	0x77, 0xb3, 0xbe, 0xb5, 0x1c, 0x6c, 0x14, 0xfe, 0xc7, 0x85, 0xfb, 0x95, 0xf6, 0xf6, 0xf7, 0xe1,
	0xca, 0x25, 0xe9, 0xe9, 0xe2, 0xdf, 0xe2, 0xdc, 0xdd, 0x01, 0xbd, 0x5c, 0x48, 0xed, 0x55, 0xa4,
	0x7e, 0xe0, 0xed, 0xd5, 0x06, 0xbf, 0xd4, 0xa0, 0x7b, 0x8c, 0x52, 0x1d, 0xa2, 0x90, 0x3c, 0xa5,
	0xe4, 0x2e, 0xb4, 0x33, 0x57, 0xba, 0x39, 0xa0, 0xbb, 0xdb, 0x3b, 0x4f, 0x49, 0x50, 0x46, 0xe8,
	0xab, 0x45, 0xa3, 0x08, 0xa5, 0x2d, 0xb7, 0x13, 0x38, 0x8b, 0xdc, 0x01, 0x2f, 0x67, 0x7e, 0xdd,
	0x50, 0x70, 0xad, 0xd8, 0x5f, 0xf9, 0xcc, 0xf0, 0x25, 0xb3, 0x4c, 0x7a, 0x39, 0xeb, 0x7f, 0x0a,
	0x2d, 0x67, 0xfe, 0xa3, 0xcc, 0xbf, 0xab, 0x43, 0xf7, 0x10, 0xc5, 0x94, 0x49, 0x69, 0x68, 0xf4,
	0xa1, 0x35, 0x43, 0xa1, 0xd7, 0x6e, 0x7f, 0x61, 0xea, 0x8b, 0x22, 0x70, 0xc6, 0x64, 0xd1, 0x89,
	0xea, 0x41, 0x69, 0xeb, 0x0e, 0xa2, 0xd3, 0x63, 0x2a, 0x54, 0x6c, 0x6a, 0x9f, 0x42, 0x2d, 0x00,
	0x0b, 0x1d, 0xb3, 0x29, 0x92, 0xfb, 0xd0, 0xc8, 0x25, 0x0a, 0xe9, 0x2f, 0x99, 0x6a, 0x6e, 0x94,
	0x6c, 0x2c, 0x3e, 0x3d, 0x7c, 0xa9, 0x03, 0x6c, 0x41, 0x36, 0xb8, 0xff, 0x7d, 0x0d, 0x56, 0x17,
	0x11, 0xda, 0x4f, 0x0e, 0xa0, 0x21, 0x78, 0x82, 0xc5, 0x4d, 0xdb, 0xbe, 0xec, 0xa0, 0xb3, 0x5b,
	0x86, 0x81, 0x8e, 0x77, 0xe7, 0x9a, 0xbd, 0xfd, 0x3d, 0x80, 0x05, 0xf8, 0x3e, 0xba, 0xea, 0x15,
	0xba, 0xfa, 0x5f, 0x01, 0x2c, 0xd2, 0xbc, 0x64, 0xe7, 0x5e, 0x75, 0x67, 0x77, 0x77, 0xf0, 0xfe,
	0xf4, 0xaa, 0x62, 0xfc, 0x5e, 0x03, 0x78, 0xc6, 0xc7, 0x2c, 0x3d, 0x52, 0x54, 0x21, 0xf9, 0x2f,
	0xb4, 0x59, 0x9c, 0x85, 0x29, 0x9d, 0x16, 0xad, 0xa8, 0xc5, 0xe2, 0xec, 0x4b, 0x3a, 0x35, 0x5d,
	0x47, 0x20, 0x4d, 0xa6, 0x85, 0xa0, 0xc6, 0x20, 0x37, 0xa1, 0x13, 0x25, 0x0c, 0x53, 0x15, 0xb2,
	0xd8, 0xf6, 0xa3, 0x87, 0x9e, 0x5f, 0x0b, 0xda, 0x16, 0x7c, 0x1a, 0xeb, 0x6d, 0x32, 0xe2, 0xe5,
	0x5c, 0xb0, 0x06, 0xb9, 0xa1, 0x95, 0x8d, 0x99, 0xc0, 0xc8, 0x4e, 0x06, 0xb7, 0xab, 0xc0, 0x88,
	0x0f, 0x0d, 0xa9, 0x13, 0xb2, 0x5d, 0xc3, 0x38, 0x2d, 0xa0, 0x3d, 0x29, 0x4f, 0x23, 0xf4, 0x9b,
	0x0b, 0x8f, 0x01, 0xc8, 0x75, 0xe8, 0x44, 0x13, 0x9a, 0x24, 0x98, 0x8e, 0xd1, 0x8d, 0x89, 0x05,
	0x30, 0xf8, 0xd9, 0x83, 0xd5, 0xfd, 0x5c, 0x4d, 0x8e, 0xf9, 0x5b, 0x74, 0xc5, 0x56, 0x93, 0xa8,
	0x5d, 0x9a, 0x44, 0x4b, 0xe6, 0x27, 0x6f, 0xb4, 0xdb, 0xd6, 0x5c, 0x98, 0x8b, 0xa2, 0xea, 0xd5,
	0xa2, 0xfa, 0xd0, 0xce, 0x04, 0x9f, 0xb1, 0x18, 0x85, 0xab, 0xb6, 0xb4, 0x17, 0xec, 0x35, 0xaa,
	0xec, 0x95, 0x65, 0xb6, 0xff, 0x7e, 0x99, 0xff, 0x03, 0x48, 0xb4, 0x60, 0xe1, 0x84, 0xa5, 0xca,
	0x75, 0xd5, 0x8e, 0x41, 0x9e, 0xb0, 0x54, 0xe9, 0x31, 0x10, 0xf1, 0x54, 0x6a, 0x45, 0x16, 0x6c,
	0xd8, 0xc1, 0xd8, 0x73, 0x8e, 0x83, 0x02, 0x37, 0x9d, 0x38, 0x8f, 0x19, 0xea, 0x0f, 0x81, 0x69,
	0x04, 0xa5, 0x3d, 0x78, 0x0d, 0x2b, 0x86, 0xab, 0xe7, 0xa8, 0x68, 0x4c, 0x15, 0xd5, 0x23, 0xaa,
	0x72, 0x2f, 0xcc, 0x9a, 0x5c, 0x83, 0x0e, 0x93, 0x32, 0xc7, 0x38, 0xa4, 0x05, 0x49, 0x6d, 0x0b,
	0xec, 0x1b, 0xfe, 0xdc, 0x30, 0x71, 0x3c, 0x15, 0xe6, 0xe0, 0x47, 0x0f, 0x96, 0x9f, 0x30, 0xa9,
	0xb8, 0x98, 0xdb, 0x6b, 0x5d, 0x7d, 0xe9, 0xb5, 0x73, 0x2f, 0x9d, 0xc0, 0x92, 0x7e, 0x9b, 0xee,
	0x78, 0xb3, 0x7e, 0xff, 0xeb, 0x27, 0xb0, 0x94, 0x51, 0x35, 0x29, 0x7e, 0x8d, 0xe8, 0xb5, 0xd6,
	0xe0, 0x5d, 0x8e, 0x62, 0x5e, 0x68, 0x60, 0x0c, 0x1d, 0xa9, 0x7f, 0xde, 0x58, 0xa2, 0x03, 0xb3,
	0xd6, 0xed, 0x71, 0x8a, 0x6a, 0xc2, 0x63, 0xc7, 0xaf, 0xb3, 0xcc, 0x67, 0x27, 0x34, 0x1d, 0x63,
	0x68, 0x86, 0xb5, 0xbd, 0x64, 0x60, 0xa1, 0x63, 0x3d, 0xb2, 0x3f, 0x80, 0x55, 0x2e, 0xd8, 0x98,
	0xe9, 0x91, 0x50, 0xfd, 0x4d, 0xb2, 0x52, 0xa0, 0xe6, 0x47, 0x89, 0x0e, 0x73, 0xe7, 0x08, 0x7c,
	0x97, 0xa3, 0x54, 0x3e, 0xd8, 0x30, 0x8b, 0x06, 0x16, 0x1c, 0x50, 0x68, 0x39, 0x96, 0xc8, 0x10,
	0x5a, 0x13, 0xbb, 0x74, 0x6d, 0xa8, 0x9c, 0xbd, 0x55, 0x1e, 0x83, 0x22, 0x88, 0xdc, 0x86, 0xb5,
	0x14, 0x4f, 0x55, 0x98, 0x51, 0x9d, 0xac, 0xd6, 0xd1, 0xf1, 0xb7, 0xa2, 0xe1, 0x43, 0x3a, 0x46,
	0x23, 0xee, 0xe0, 0x37, 0x0f, 0xe0, 0x05, 0x8b, 0xa3, 0x03, 0x9e, 0x8e, 0xd8, 0x58, 0x17, 0x6e,
	0xe4, 0x13, 0x4e, 0x65, 0x67, 0x69, 0x7d, 0xde, 0x7c, 0xf3, 0x56, 0x86, 0xb9, 0x60, 0x85, 0xcc,
	0x85, 0x4d, 0xb6, 0x61, 0x85, 0xe6, 0x6a, 0x12, 0x62, 0x1a, 0x67, 0x5c, 0xdf, 0x49, 0x2b, 0xf6,
	0x86, 0x06, 0xb9, 0x60, 0xdf, 0x9a, 0x9f, 0x11, 0xa5, 0x97, 0x3c, 0x00, 0x5f, 0xa0, 0xcc, 0xf4,
	0x55, 0x34, 0x2c, 0xca, 0x50, 0xe6, 0x99, 0x1e, 0x4a, 0x18, 0x9b, 0x56, 0xdd, 0x09, 0xfe, 0xd2,
	0x4f, 0x6e, 0xc3, 0xaa, 0xa9, 0x65, 0xf1, 0x2d, 0x2b, 0xe5, 0x39, 0x94, 0xdc, 0x83, 0x2b, 0x02,
	0x67, 0x3c, 0x3a, 0xfb, 0x69, 0xa7, 0xd7, 0x65, 0x2e, 0x72, 0x17, 0xd6, 0xf5, 0xc5, 0x62, 0xe9,
	0x88, 0x2f, 0xe2, 0xed, 0x95, 0xb8, 0xe8, 0x20, 0x1f, 0x41, 0xcf, 0x3c, 0xf9, 0x6a, 0xee, 0x2d,
	0x93, 0xfb, 0x05, 0x7c, 0xf0, 0xab, 0x07, 0xeb, 0x9a, 0x61, 0xc3, 0x77, 0xe0, 0x2a, 0x23, 0x03,
	0x58, 0xb6, 0x23, 0xd7, 0x89, 0x63, 0xe9, 0x3e, 0x83, 0x91, 0x1b, 0x00, 0xb6, 0x2e, 0x73, 0xd9,
	0x2c, 0xed, 0x15, 0x44, 0xfb, 0x8b, 0x1f, 0x71, 0x2c, 0x35, 0xac, 0x37, 0x82, 0x0a, 0x42, 0x6e,
	0xc1, 0x8a, 0xc0, 0x91, 0x40, 0x39, 0x71, 0x1f, 0xb1, 0x8f, 0xe1, 0x2c, 0xa8, 0xa5, 0x65, 0xb1,
	0x0b, 0x68, 0xb8, 0x17, 0xec, 0xec, 0x45, 0x9f, 0x6b, 0x56, 0xfb, 0x5c, 0x0f, 0xea, 0x39, 0x2b,
	0x9e, 0x86, 0x5e, 0x92, 0x5d, 0x58, 0xd2, 0x04, 0x19, 0x82, 0x2b, 0xa3, 0xf6, 0x42, 0xd9, 0xc3,
	0xa7, 0xe9, 0x88, 0x07, 0x26, 0xb6, 0x7f, 0x0f, 0x96, 0xb4, 0x75, 0x69, 0x5b, 0xb9, 0x0a, 0x0d,
	0x9c, 0x52, 0x96, 0x14, 0xb3, 0xc6, 0x18, 0x0f, 0x5f, 0xbe, 0x3e, 0x1a, 0x33, 0x35, 0xc9, 0x4f,
	0xf4, 0xf9, 0x3b, 0x5f, 0x70, 0x3e, 0x4e, 0xf0, 0x20, 0xe1, 0x79, 0x7c, 0x98, 0x50, 0x35, 0xe2,
	0x62, 0xba, 0x33, 0x41, 0x9a, 0xa8, 0x49, 0x44, 0x05, 0x6e, 0x8f, 0x30, 0x46, 0x41, 0x15, 0xc6,
	0xdb, 0x96, 0xd3, 0x6d, 0x89, 0x62, 0xc6, 0x22, 0x94, 0x3b, 0xe7, 0xfe, 0x2c, 0x9d, 0x34, 0x0d,
	0xf0, 0xc9, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd6, 0xa2, 0x7d, 0xdc, 0x46, 0x0d, 0x00, 0x00,
}
