// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/process/v1/process.proto

// Package process provides protocol buffers for background process state.

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Process_Status_State int32

const (
	Process_Status_UNSPECIFIED Process_Status_State = 0
	Process_Status_NEW         Process_Status_State = 1
	Process_Status_ACTIVE      Process_Status_State = 2
	Process_Status_ABORTED     Process_Status_State = 3
	Process_Status_INCOMPLETE  Process_Status_State = 4
	Process_Status_COMPLETED   Process_Status_State = 5
)

var Process_Status_State_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "NEW",
	2: "ACTIVE",
	3: "ABORTED",
	4: "INCOMPLETE",
	5: "COMPLETED",
}

var Process_Status_State_value = map[string]int32{
	"UNSPECIFIED": 0,
	"NEW":         1,
	"ACTIVE":      2,
	"ABORTED":     3,
	"INCOMPLETE":  4,
	"COMPLETED":   5,
}

func (x Process_Status_State) String() string {
	return proto.EnumName(Process_Status_State_name, int32(x))
}

func (Process_Status_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b24df3f2bd7a2000, []int{0, 2, 0}
}

// Background process state
type Process struct {
	// Name of the process.
	ProcessName string `protobuf:"bytes,1,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	// A GUID or other unique identifier for the last process instance that has
	// updated the process. This is a means of tracking state as multiple
	// background processes can attempt to grab and lock process state. It may
	// be used as a means to detect that locks have been lost.
	Instance string `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	// Frequency of how often a process is scheduled to start processing.
	ScheduleFrequency *duration.Duration `protobuf:"bytes,3,opt,name=schedule_frequency,json=scheduleFrequency,proto3" json:"schedule_frequency,omitempty"`
	// List of active projects being processed.
	ActiveProjects map[string]*Process_Project `protobuf:"bytes,4,rep,name=active_projects,json=activeProjects,proto3" json:"active_projects,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Projects to be dropped during a future active period. Is a map of
	// project name to timestamp of request.
	CleanupProjects map[string]*timestamp.Timestamp `protobuf:"bytes,5,rep,name=cleanup_projects,json=cleanupProjects,proto3" json:"cleanup_projects,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Projects that are no longer active (i.e. dropped) as a form of tracking
	// previous state. Is a map of project name to timestamp of when the project
	// was dropped.
	DroppedProjects map[string]*timestamp.Timestamp `protobuf:"bytes,6,rep,name=dropped_projects,json=droppedProjects,proto3" json:"dropped_projects,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Input parameters of the project.
	Settings *Process_Params `protobuf:"bytes,7,opt,name=settings,proto3" json:"settings,omitempty"`
	// Time of most recent change to the ProcessStatus.Params settings.
	SettingsTime *timestamp.Timestamp `protobuf:"bytes,8,opt,name=settings_time,json=settingsTime,proto3" json:"settings_time,omitempty"`
	// Status over all projects for the most recent period or active period.
	ProcessStatus *Process_Status `protobuf:"bytes,9,opt,name=process_status,json=processStatus,proto3" json:"process_status,omitempty"`
	// Aggregate stats over all projects and time periods since last reset.
	AggregateStats       map[string]float64 `protobuf:"bytes,10,rep,name=aggregate_stats,json=aggregateStats,proto3" json:"aggregate_stats,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Process) Reset()         { *m = Process{} }
func (m *Process) String() string { return proto.CompactTextString(m) }
func (*Process) ProtoMessage()    {}
func (*Process) Descriptor() ([]byte, []int) {
	return fileDescriptor_b24df3f2bd7a2000, []int{0}
}

func (m *Process) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Process.Unmarshal(m, b)
}
func (m *Process) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Process.Marshal(b, m, deterministic)
}
func (m *Process) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Process.Merge(m, src)
}
func (m *Process) XXX_Size() int {
	return xxx_messageInfo_Process.Size(m)
}
func (m *Process) XXX_DiscardUnknown() {
	xxx_messageInfo_Process.DiscardUnknown(m)
}

var xxx_messageInfo_Process proto.InternalMessageInfo

func (m *Process) GetProcessName() string {
	if m != nil {
		return m.ProcessName
	}
	return ""
}

func (m *Process) GetInstance() string {
	if m != nil {
		return m.Instance
	}
	return ""
}

func (m *Process) GetScheduleFrequency() *duration.Duration {
	if m != nil {
		return m.ScheduleFrequency
	}
	return nil
}

func (m *Process) GetActiveProjects() map[string]*Process_Project {
	if m != nil {
		return m.ActiveProjects
	}
	return nil
}

func (m *Process) GetCleanupProjects() map[string]*timestamp.Timestamp {
	if m != nil {
		return m.CleanupProjects
	}
	return nil
}

func (m *Process) GetDroppedProjects() map[string]*timestamp.Timestamp {
	if m != nil {
		return m.DroppedProjects
	}
	return nil
}

func (m *Process) GetSettings() *Process_Params {
	if m != nil {
		return m.Settings
	}
	return nil
}

func (m *Process) GetSettingsTime() *timestamp.Timestamp {
	if m != nil {
		return m.SettingsTime
	}
	return nil
}

func (m *Process) GetProcessStatus() *Process_Status {
	if m != nil {
		return m.ProcessStatus
	}
	return nil
}

func (m *Process) GetAggregateStats() map[string]float64 {
	if m != nil {
		return m.AggregateStats
	}
	return nil
}

// Error message that is kept in context with the background process
// for debugging.
type Process_Error struct {
	// Timestamp of the error.
	Time *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	// Error message.
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Process_Error) Reset()         { *m = Process_Error{} }
func (m *Process_Error) String() string { return proto.CompactTextString(m) }
func (*Process_Error) ProtoMessage()    {}
func (*Process_Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_b24df3f2bd7a2000, []int{0, 0}
}

func (m *Process_Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Process_Error.Unmarshal(m, b)
}
func (m *Process_Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Process_Error.Marshal(b, m, deterministic)
}
func (m *Process_Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Process_Error.Merge(m, src)
}
func (m *Process_Error) XXX_Size() int {
	return xxx_messageInfo_Process_Error.Size(m)
}
func (m *Process_Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Process_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Process_Error proto.InternalMessageInfo

func (m *Process_Error) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *Process_Error) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

// Input parameters configured for the background process that control
// its behavior.
type Process_Params struct {
	// Process-specific map of integer parameter name to parameter value.
	IntParams map[string]int64 `protobuf:"bytes,1,rep,name=int_params,json=intParams,proto3" json:"int_params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	// Process-specific map of string parameter name to parameter value.
	StringParams         map[string]string `protobuf:"bytes,2,rep,name=string_params,json=stringParams,proto3" json:"string_params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Process_Params) Reset()         { *m = Process_Params{} }
func (m *Process_Params) String() string { return proto.CompactTextString(m) }
func (*Process_Params) ProtoMessage()    {}
func (*Process_Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_b24df3f2bd7a2000, []int{0, 1}
}

func (m *Process_Params) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Process_Params.Unmarshal(m, b)
}
func (m *Process_Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Process_Params.Marshal(b, m, deterministic)
}
func (m *Process_Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Process_Params.Merge(m, src)
}
func (m *Process_Params) XXX_Size() int {
	return xxx_messageInfo_Process_Params.Size(m)
}
func (m *Process_Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Process_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Process_Params proto.InternalMessageInfo

func (m *Process_Params) GetIntParams() map[string]int64 {
	if m != nil {
		return m.IntParams
	}
	return nil
}

func (m *Process_Params) GetStringParams() map[string]string {
	if m != nil {
		return m.StringParams
	}
	return nil
}

// Execution status for a particular run or snapshot of the process.
type Process_Status struct {
	// Time period start.
	StartTime *timestamp.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Time of last progress status update. This will be equal to the
	// finish_time if the processing has completed.
	ProgressTime *timestamp.Timestamp `protobuf:"bytes,2,opt,name=progress_time,json=progressTime,proto3" json:"progress_time,omitempty"`
	// Time period end.
	FinishTime *timestamp.Timestamp `protobuf:"bytes,3,opt,name=finish_time,json=finishTime,proto3" json:"finish_time,omitempty"`
	// Time of most recent error.
	LastErrorTime *timestamp.Timestamp `protobuf:"bytes,4,opt,name=last_error_time,json=lastErrorTime,proto3" json:"last_error_time,omitempty"`
	// Statistics collected of statistic label to statistic value.
	Stats map[string]float64 `protobuf:"bytes,5,rep,name=stats,proto3" json:"stats,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	// Recent errors, which may have less entries than total errors to reduce
	// space and noise.
	Errors []*Process_Error `protobuf:"bytes,6,rep,name=errors,proto3" json:"errors,omitempty"`
	// Total number of errors before the process completed or aborted.
	TotalErrors          int64                `protobuf:"varint,7,opt,name=total_errors,json=totalErrors,proto3" json:"total_errors,omitempty"`
	State                Process_Status_State `protobuf:"varint,8,opt,name=state,proto3,enum=process.Process_Status_State" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Process_Status) Reset()         { *m = Process_Status{} }
func (m *Process_Status) String() string { return proto.CompactTextString(m) }
func (*Process_Status) ProtoMessage()    {}
func (*Process_Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_b24df3f2bd7a2000, []int{0, 2}
}

func (m *Process_Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Process_Status.Unmarshal(m, b)
}
func (m *Process_Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Process_Status.Marshal(b, m, deterministic)
}
func (m *Process_Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Process_Status.Merge(m, src)
}
func (m *Process_Status) XXX_Size() int {
	return xxx_messageInfo_Process_Status.Size(m)
}
func (m *Process_Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Process_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Process_Status proto.InternalMessageInfo

func (m *Process_Status) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *Process_Status) GetProgressTime() *timestamp.Timestamp {
	if m != nil {
		return m.ProgressTime
	}
	return nil
}

func (m *Process_Status) GetFinishTime() *timestamp.Timestamp {
	if m != nil {
		return m.FinishTime
	}
	return nil
}

func (m *Process_Status) GetLastErrorTime() *timestamp.Timestamp {
	if m != nil {
		return m.LastErrorTime
	}
	return nil
}

func (m *Process_Status) GetStats() map[string]float64 {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *Process_Status) GetErrors() []*Process_Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *Process_Status) GetTotalErrors() int64 {
	if m != nil {
		return m.TotalErrors
	}
	return 0
}

func (m *Process_Status) GetState() Process_Status_State {
	if m != nil {
		return m.State
	}
	return Process_Status_UNSPECIFIED
}

// Processes may act on a set of projects, and may have different input
// parameters per project.
type Process_Project struct {
	// Time when the project settings were last modified.
	Modified *timestamp.Timestamp `protobuf:"bytes,1,opt,name=modified,proto3" json:"modified,omitempty"`
	// Input parameters of the project. These will vary depending on the needs
	// of process workers that may need input parameters to complete their work.
	// Example: if there were a rename process that occationally updates the
	// names of objects in the storage layer, then it may have params of:
	//   {
	//     "stringParams": {
	//       "find": "old_name",
	//       "replace": "new_name"
	//     }
	//     "intParams": {
	//       "maxReplacements": 1
	//     }
	//   }
	// Note: this structure allows input parameters to vary between projects.
	Params *Process_Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	// Project status. Changes here do not cause "modified" settings timestamp
	// to change.
	Status               *Process_Status `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Process_Project) Reset()         { *m = Process_Project{} }
func (m *Process_Project) String() string { return proto.CompactTextString(m) }
func (*Process_Project) ProtoMessage()    {}
func (*Process_Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_b24df3f2bd7a2000, []int{0, 3}
}

func (m *Process_Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Process_Project.Unmarshal(m, b)
}
func (m *Process_Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Process_Project.Marshal(b, m, deterministic)
}
func (m *Process_Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Process_Project.Merge(m, src)
}
func (m *Process_Project) XXX_Size() int {
	return xxx_messageInfo_Process_Project.Size(m)
}
func (m *Process_Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Process_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Process_Project proto.InternalMessageInfo

func (m *Process_Project) GetModified() *timestamp.Timestamp {
	if m != nil {
		return m.Modified
	}
	return nil
}

func (m *Process_Project) GetParams() *Process_Params {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *Process_Project) GetStatus() *Process_Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterEnum("process.Process_Status_State", Process_Status_State_name, Process_Status_State_value)
	proto.RegisterType((*Process)(nil), "process.Process")
	proto.RegisterMapType((map[string]*Process_Project)(nil), "process.Process.ActiveProjectsEntry")
	proto.RegisterMapType((map[string]float64)(nil), "process.Process.AggregateStatsEntry")
	proto.RegisterMapType((map[string]*timestamp.Timestamp)(nil), "process.Process.CleanupProjectsEntry")
	proto.RegisterMapType((map[string]*timestamp.Timestamp)(nil), "process.Process.DroppedProjectsEntry")
	proto.RegisterType((*Process_Error)(nil), "process.Process.Error")
	proto.RegisterType((*Process_Params)(nil), "process.Process.Params")
	proto.RegisterMapType((map[string]int64)(nil), "process.Process.Params.IntParamsEntry")
	proto.RegisterMapType((map[string]string)(nil), "process.Process.Params.StringParamsEntry")
	proto.RegisterType((*Process_Status)(nil), "process.Process.Status")
	proto.RegisterMapType((map[string]float64)(nil), "process.Process.Status.StatsEntry")
	proto.RegisterType((*Process_Project)(nil), "process.Process.Project")
}

func init() { proto.RegisterFile("proto/process/v1/process.proto", fileDescriptor_b24df3f2bd7a2000) }

var fileDescriptor_b24df3f2bd7a2000 = []byte{
	// 876 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x6d, 0x6f, 0xe3, 0x44,
	0x10, 0xc6, 0x79, 0x6d, 0x26, 0x4d, 0xea, 0xdb, 0x3b, 0x81, 0xb1, 0xc4, 0x51, 0x2a, 0x40, 0xe5,
	0x43, 0x1d, 0x68, 0x25, 0x54, 0x5e, 0x44, 0xd5, 0x26, 0x3e, 0x88, 0xe0, 0x72, 0x91, 0x1b, 0x0e,
	0x01, 0x12, 0xd1, 0xd6, 0xde, 0x38, 0x06, 0xc7, 0x0e, 0xbb, 0xeb, 0x8a, 0xfe, 0x19, 0xbe, 0xf0,
	0xb7, 0xe0, 0xbf, 0x20, 0xcf, 0xda, 0x69, 0xdc, 0xbc, 0x15, 0x89, 0x6f, 0xbb, 0xe3, 0xe7, 0x79,
	0x76, 0x32, 0xf3, 0xec, 0x6c, 0xe0, 0xf9, 0x9c, 0xc7, 0x32, 0xee, 0xcc, 0x79, 0xec, 0x32, 0x21,
	0x3a, 0xb7, 0x9f, 0xe4, 0x4b, 0x0b, 0x3f, 0x90, 0x7a, 0xb6, 0x35, 0x9f, 0xfb, 0x71, 0xec, 0x87,
	0xac, 0x83, 0xe1, 0x9b, 0x64, 0xd2, 0xf1, 0x12, 0x4e, 0x65, 0x10, 0x47, 0x0a, 0x68, 0xbe, 0xfb,
	0xf0, 0xbb, 0x0c, 0x66, 0x4c, 0x48, 0x3a, 0x9b, 0x2b, 0xc0, 0xd1, 0x3f, 0x3a, 0xd4, 0x87, 0x4a,
	0x8c, 0xbc, 0x07, 0xfb, 0x99, 0xee, 0x38, 0xa2, 0x33, 0x66, 0x68, 0x87, 0xda, 0x71, 0xc3, 0x69,
	0x66, 0xb1, 0x01, 0x9d, 0x31, 0x62, 0xc2, 0x5e, 0x10, 0x09, 0x49, 0x23, 0x97, 0x19, 0x25, 0xfc,
	0xbc, 0xd8, 0x93, 0x6f, 0x80, 0x08, 0x77, 0xca, 0xbc, 0x24, 0x64, 0xe3, 0x09, 0x67, 0xbf, 0x27,
	0x2c, 0x72, 0xef, 0x8c, 0xf2, 0xa1, 0x76, 0xdc, 0x3c, 0x7d, 0xdb, 0x52, 0x89, 0x58, 0x79, 0x22,
	0x56, 0x2f, 0x4b, 0xd4, 0x79, 0x92, 0x93, 0x5e, 0xe4, 0x1c, 0xf2, 0x12, 0x0e, 0xa8, 0x2b, 0x83,
	0x5b, 0x36, 0x9e, 0xf3, 0xf8, 0x57, 0xe6, 0x4a, 0x61, 0x54, 0x0e, 0xcb, 0xc7, 0xcd, 0xd3, 0xf7,
	0xad, 0xbc, 0x0e, 0x59, 0xce, 0xd6, 0x25, 0xe2, 0x86, 0x19, 0xcc, 0x8e, 0x24, 0xbf, 0x73, 0xda,
	0xb4, 0x10, 0x24, 0x43, 0xd0, 0xdd, 0x90, 0xd1, 0x28, 0x99, 0xdf, 0xeb, 0x55, 0x51, 0xef, 0x83,
	0x15, 0xbd, 0xae, 0x02, 0x16, 0x05, 0x0f, 0xdc, 0x62, 0x34, 0x55, 0xf4, 0x78, 0x3c, 0x9f, 0x33,
	0xef, 0x5e, 0xb1, 0xb6, 0x41, 0xb1, 0xa7, 0x80, 0x0f, 0x14, 0xbd, 0x62, 0x94, 0x9c, 0xc1, 0x9e,
	0x60, 0x52, 0x06, 0x91, 0x2f, 0x8c, 0x3a, 0x96, 0xec, 0xad, 0x15, 0xa5, 0x21, 0xe5, 0x74, 0x26,
	0x9c, 0x05, 0x90, 0x5c, 0x40, 0x2b, 0x5f, 0x8f, 0xd3, 0xc6, 0x1a, 0x7b, 0xc8, 0x34, 0x57, 0x8a,
	0x3d, 0xca, 0xbb, 0xee, 0xec, 0xe7, 0x84, 0x34, 0x44, 0xbe, 0x82, 0x76, 0xde, 0x71, 0x21, 0xa9,
	0x4c, 0x84, 0xd1, 0xd8, 0x70, 0xf6, 0x35, 0x7e, 0x76, 0x5a, 0x59, 0x5c, 0x6d, 0xb1, 0x51, 0xbe,
	0xcf, 0x99, 0x4f, 0x25, 0x43, 0x05, 0x61, 0xc0, 0xa6, 0x46, 0xe5, 0xb8, 0x94, 0xba, 0x68, 0x54,
	0x21, 0x68, 0x7e, 0x0b, 0x55, 0x9b, 0xf3, 0x98, 0x13, 0x0b, 0x2a, 0xf8, 0x7b, 0xb4, 0x9d, 0xbf,
	0x07, 0x71, 0x84, 0x40, 0x45, 0xb2, 0x3f, 0x64, 0x66, 0x49, 0x5c, 0x9b, 0x7f, 0x96, 0xa0, 0xa6,
	0x2a, 0x46, 0x6c, 0x80, 0x20, 0x92, 0xe3, 0x39, 0xee, 0x0c, 0x0d, 0x33, 0xfc, 0x70, 0x43, 0x79,
	0xad, 0x7e, 0x24, 0xd5, 0x4a, 0xe5, 0xd8, 0x08, 0xf2, 0x3d, 0x19, 0x40, 0x4b, 0x48, 0x1e, 0x44,
	0x7e, 0xae, 0x54, 0x42, 0xa5, 0x8f, 0x36, 0x29, 0x5d, 0x23, 0x78, 0x59, 0x6c, 0x5f, 0x2c, 0x85,
	0xcc, 0x2f, 0xa1, 0x5d, 0x3c, 0x8c, 0xe8, 0x50, 0xfe, 0x8d, 0xdd, 0x65, 0x17, 0x2f, 0x5d, 0x92,
	0x67, 0x50, 0xbd, 0xa5, 0x61, 0xa2, 0x6e, 0x5b, 0xd9, 0x51, 0x9b, 0xcf, 0x4b, 0xe7, 0x9a, 0x79,
	0x01, 0x4f, 0x56, 0x0e, 0xd8, 0x25, 0xd0, 0x58, 0x16, 0xf8, 0xbb, 0x02, 0xb5, 0xac, 0x8f, 0x9f,
	0x01, 0x08, 0x49, 0xb9, 0x1c, 0x3f, 0xb2, 0xea, 0x0d, 0x44, 0xa3, 0x85, 0x2e, 0x20, 0xf5, 0x84,
	0xcf, 0x53, 0x0f, 0x21, 0xbb, 0xb4, 0xdb, 0x83, 0x39, 0x01, 0x05, 0xbe, 0x80, 0xe6, 0x24, 0x88,
	0x02, 0x31, 0x55, 0xf4, 0xf2, 0x4e, 0x3a, 0x28, 0x38, 0x92, 0xaf, 0xe0, 0x20, 0xa4, 0x42, 0x8e,
	0x59, 0x6a, 0x1b, 0x25, 0x50, 0xd9, 0x29, 0xd0, 0x4a, 0x29, 0x68, 0x34, 0xd4, 0x38, 0x87, 0xaa,
	0xb2, 0xae, 0x9a, 0x09, 0x47, 0x1b, 0xbc, 0x6f, 0x2d, 0x19, 0x57, 0x11, 0x88, 0x05, 0x35, 0x3c,
	0x38, 0xbf, 0xfc, 0x6f, 0xae, 0x50, 0xf1, 0x14, 0x27, 0x43, 0xa5, 0x03, 0x56, 0xc6, 0x92, 0x86,
	0xe3, 0x8c, 0x55, 0xc7, 0x9e, 0x36, 0x31, 0x66, 0x2b, 0xc8, 0x99, 0x4a, 0x46, 0x5d, 0xe5, 0xf6,
	0xe9, 0x3b, 0xdb, 0x92, 0x61, 0x2a, 0x0f, 0x66, 0x9e, 0x03, 0xdc, 0x27, 0xb7, 0xcb, 0x03, 0xda,
	0x92, 0x07, 0x8e, 0x7e, 0x84, 0x2a, 0x2a, 0x91, 0x03, 0x68, 0x7e, 0x3f, 0xb8, 0x1e, 0xda, 0xdd,
	0xfe, 0x8b, 0xbe, 0xdd, 0xd3, 0xdf, 0x20, 0x75, 0x28, 0x0f, 0xec, 0x1f, 0x74, 0x8d, 0x00, 0xd4,
	0x2e, 0xbb, 0xa3, 0xfe, 0x6b, 0x5b, 0x2f, 0x91, 0x26, 0xd4, 0x2f, 0xaf, 0x5e, 0x39, 0x23, 0xbb,
	0xa7, 0x97, 0x49, 0x1b, 0xa0, 0x3f, 0xe8, 0xbe, 0x7a, 0x39, 0xfc, 0xce, 0x1e, 0xd9, 0x7a, 0x85,
	0xb4, 0xa0, 0x91, 0xef, 0x7a, 0x7a, 0xd5, 0xfc, 0x4b, 0xc3, 0x97, 0x25, 0x1d, 0x6f, 0xe4, 0x53,
	0xd8, 0x9b, 0xc5, 0x5e, 0x30, 0x09, 0x98, 0xf7, 0x08, 0x77, 0x2d, 0xb0, 0xa4, 0x03, 0xb5, 0xc5,
	0x55, 0xdb, 0x3a, 0x13, 0x33, 0x58, 0x4a, 0xc8, 0x06, 0x59, 0x79, 0xfb, 0x20, 0xcb, 0x60, 0xe6,
	0xcf, 0xf0, 0x74, 0xcd, 0x13, 0xb2, 0xa6, 0x86, 0xd6, 0x72, 0x0d, 0x9b, 0xa7, 0xc6, 0x6a, 0x26,
	0x4a, 0x60, 0xf9, 0x86, 0xfd, 0x02, 0xcf, 0xd6, 0xbd, 0x27, 0x6b, 0xd4, 0x3f, 0x2e, 0xaa, 0x6f,
	0xab, 0x4e, 0x51, 0x7f, 0xdd, 0xeb, 0xf2, 0xbf, 0xe9, 0x5f, 0xc2, 0xd3, 0x35, 0x63, 0xfb, 0xbf,
	0x18, 0xec, 0xea, 0xf5, 0x4f, 0x23, 0x3f, 0x90, 0xd3, 0xe4, 0xc6, 0x72, 0xe3, 0x59, 0xe7, 0x6b,
	0x3c, 0xb5, 0x1b, 0xc6, 0x89, 0x37, 0x0c, 0xa9, 0x9c, 0xc4, 0x7c, 0xd6, 0x99, 0x32, 0x1a, 0xca,
	0xa9, 0x4b, 0x39, 0x3b, 0x99, 0x30, 0x8f, 0x71, 0x2a, 0x99, 0x77, 0x42, 0xdd, 0xb4, 0xa6, 0x27,
	0x82, 0xf1, 0xdb, 0xc0, 0x65, 0xa2, 0xf3, 0xf0, 0xff, 0xd0, 0x4d, 0x0d, 0x23, 0x67, 0xff, 0x06,
	0x00, 0x00, 0xff, 0xff, 0x9d, 0xb2, 0x79, 0x99, 0x2a, 0x09, 0x00, 0x00,
}
